/* Detailed cultivation workshops: real thermal control, inscribed gear and paid production orders. */
(function(root,factory){'use strict';const make=factory();if(typeof module==='object'&&module.exports)module.exports=make;if(root)root.XianWorkshop=make;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),copy=o=>JSON.parse(JSON.stringify(o));
  const CATALYSTS={wood:{id:'wood',name:'灵木药引',description:'炉温偏柔，初始纯净度 +8，成丹多1份。',cost:{spiritwood:1},heatOffset:-5,purityBonus:8,yieldBonus:1},frost:{id:'frost',name:'寒晶药引',description:'炉温降低15度，初始纯净度 +16，适合寒性丹方。',cost:{frost:1},heatOffset:-15,purityBonus:16,yieldBonus:0},ember:{id:'ember',name:'赤砂药引',description:'炉温提高10度，初始纯净度 -10，成丹多2份。',cost:{ember:1},heatOffset:10,purityBonus:-10,yieldBonus:2},essence:{id:'essence',name:'灵髓药引',description:'炉温提高5度，初始纯净度 +24，昂贵但适合精制。',cost:{essence:1},heatOffset:5,purityBonus:24,yieldBonus:0}};
  const PATTERNS={edge:{id:'edge',name:'锋锐纹',description:'换取更强攻击，但削弱气血。',stats:{attack:12,maxHp:-18}},guard:{id:'guard',name:'守御纹',description:'抵御重击，但身法稍缓。',stats:{defense:5,speed:-10}},spirit:{id:'spirit',name:'聚灵纹',description:'增加灵力和回复，但剑锋稍弱。',stats:{maxMp:28,manaRegen:.45,attack:-3}},swift:{id:'swift',name:'轻身纹',description:'提高移动速度，但减少防御。',stats:{speed:18,defense:-2}}};
  const TEMPER={water:{id:'water',label:'清水急淬',description:'3秒完成，不另耗材料，刻纹质量较低。',cost:{},duration:3,qualityBonus:0},wood:{id:'wood',label:'灵木缓淬',description:'6秒，消耗1灵木，刻纹质量提升一档。',cost:{spiritwood:1},duration:6,qualityBonus:1},frost:{id:'frost',label:'寒晶定纹',description:'6秒，消耗2寒晶，质量提升一档并额外稳定刻纹。',cost:{frost:2},duration:6,qualityBonus:1.3}};
  const FIRE=[{id:'0',label:'停火散热',target:20},{id:'1',label:'文火',target:50},{id:'2',label:'平火',target:80},{id:'3',label:'武火',target:110}];
  const BREWS={healing:{target:62,base:'potions',effect:'healing',label:'回春丹',realm:0},tea:{target:42,base:'spiritTea',effect:'mana',label:'凝神茶',realm:0},ward:{target:72,base:'wardPowder',effect:'ward',label:'护体散',realm:0},rage:{target:88,base:'rageElixir',effect:'rage',label:'赤阳丹',realm:1},insight:{target:52,base:'insightPill',effect:'insight',label:'通灵丹',realm:1}};
  const QUALITY=['寻常','精制','上品'];
  const POSITIONS=[{id:'east',label:'东方木位',element:'wood'},{id:'south',label:'南方火位',element:'fire'},{id:'center',label:'中央土位',element:'earth'},{id:'west',label:'西方金位',element:'metal'},{id:'north',label:'北方水位',element:'water'}];
  const GENERATES={wood:'fire',fire:'earth',earth:'metal',metal:'water',water:'wood'};
  const POLICIES={balanced:{id:'balanced',name:'平衡轮值',speed:1,fatigue:.45,threshold:64,recoverTo:20,extraCost:{}},urgent:{id:'urgent',name:'赶工',speed:1.35,fatigue:.8,threshold:88,recoverTo:30,extraCost:{herbs:1}},careful:{id:'careful',name:'保养慢工',speed:.8,fatigue:.2,threshold:50,recoverTo:12,extraCost:{}}};
  const ORDERS={
    herbs:{id:'herbs',facility:'garden',name:'育草',description:'投入种草，产出炼丹所需灵草。',element:'wood',duration:18,cost:{herbs:1},reward:{herbs:4}},
    timber:{id:'timber',facility:'garden',name:'培育灵木',description:'把草木灵气养成药引与器物辅材。',element:'wood',duration:24,cost:{herbs:1,stones:3},reward:{spiritwood:2}},
    seed:{id:'seed',facility:'garden',name:'药引温床',description:'灵木与赤砂制药引，所得妖丹用于丹方和破境。',element:'earth',duration:30,cost:{spiritwood:1,ember:1,herbs:1},reward:{herbs:3,core:1}},
    iron:{id:'iron',facility:'forge',name:'精炼玄铁',description:'消耗炉用灵草和灵石，提供器物主材。',element:'metal',duration:20,cost:{stones:4,herbs:1},reward:{iron:3}},
    ember:{id:'ember',facility:'forge',name:'凝聚赤砂',description:'玄铁吸取火脉，制成武火与赤阳药引。',element:'fire',duration:26,cost:{iron:1,stones:5},reward:{ember:2}},
    essence:{id:'essence',facility:'forge',name:'提取灵髓',description:'妖丹与玄铁合炼，供应高阶研究、功法和丹药。',element:'fire',duration:36,cost:{core:1,iron:2,stones:8},reward:{essence:1}},
    insight:{id:'insight',facility:'library',name:'推演法意',description:'消耗灵草、灵石，得到真实修为。',element:'water',duration:26,cost:{stones:5,herbs:1},reward:{xp:65}},
    research:{id:'research',facility:'library',name:'研习工艺',description:'最多三级，改善丹炉控温稳定与器物刻纹。',element:'water',duration:42,cost:{essence:1,spiritwood:1,contribution:2},reward:{research:1}},
    service:{id:'service',facility:'library',name:'整理山门典籍',description:'持续耗材换贡献，供日后传承和领用。',element:'metal',duration:34,cost:{spiritwood:2,stones:8},reward:{contribution:5}}
  };
  for(const catalog of [CATALYSTS,PATTERNS,TEMPER,POLICIES,ORDERS,BREWS])Object.setPrototypeOf(catalog,null);
  return function createWorkshop(CONTENT,h){
    const MEDICINES=Object.create(null);for(const [id,r]of Object.entries(BREWS))for(const q of [1,2]){const itemId=`${id}_${q===1?'fine':'pure'}`,effect=r.effect,potency={healing:[.52,.64],mana:[.68,.82],ward:[.32,.44],rage:[.32,.42],insight:[.4,.5]}[effect][q-1],duration=effect==='insight'?[60,80][q-1]:[40,50][q-1];
      const effectText=effect==='healing'?`恢复${Math.round(potency*100)}%气血和${q===1?35:45}%灵力。`:effect==='mana'?`恢复${Math.round(potency*100)}%灵力。`:effect==='ward'?`${duration}秒内承伤降低${Math.round(potency*100)}%，与普通护体散取较强者。`:effect==='rage'?`${duration}秒内攻击提高${Math.round(potency*100)}%，与赤阳丹取较强者。`:`${duration}秒内获取修为提高${Math.round(potency*100)}%，与通灵丹取较强者。`;
      MEDICINES[itemId]={id:itemId,recipeId:id,name:`${QUALITY[q]}${r.label}`,type:'consumable',grade:QUALITY[q],description:effectText,effect:'workshop',medicineEffect:effect,quality:q,potency,duration};CONTENT.ITEMS[itemId]=MEDICINES[itemId];}
    const merge=(...all)=>{const o={};for(const a of all)for(const[k,v]of Object.entries(a||{}))o[k]=(o[k]||0)+v;return o;};
    const same=(a,b)=>JSON.stringify(Object.entries(a).sort())===JSON.stringify(Object.entries(b).sort());
    const entry=(o,key)=>Object.hasOwn(o,key)?o[key]:null;
    const station=(s,kind,map)=>kind==='brew'?h.alchemyStation(s,map):(()=>{const n=CONTENT.MAPS[s.mapId]?.npcs.find(n=>n.id==='forge'),near=!s.activity&&s.mapId===(map||s.mapId)&&!!n&&Math.hypot(s.player.x-n.x,s.player.y-n.y)<=115;return{near,reason:s.dead?'先重聚灵身。':!near?'请返回开炉时的原铸剑台。':!h.isSafe(s)?'铸造须在安全铸台进行。':''};})();
    const init=s=>{s.workshop={brew:null,forge:null,mods:{},medicineBuffs:{},research:0};s.management={enabled:false,facilities:{},workers:{}};for(const id of Object.keys(CONTENT.SECT_FACILITIES))s.management.facilities[id]={position:CONTENT.SECT_FACILITIES[id].position,order:null,batch:null,stored:[],carry:0};for(const id of Object.keys(CONTENT.SECT_DISCIPLES))s.management.workers[id]={fatigue:0,policy:'balanced',resting:false};};
    const brewQuality=a=>{const score=a.stable/16*.65+a.purity/100*.35+(a.seal==='slow'?.09:0);return Math.min(a.seal==='fast'?1:2,score>=.84?2:score>=.58?1:0);};
    function brewOutput(a){const spec=BREWS[a.recipeId],q=brewQuality(a),id=q===0?spec.base:`${a.recipeId}_${q===1?'fine':'pure'}`,n=Object.values(CONTENT.RECIPES[a.recipeId].output)[0]+CATALYSTS[a.catalystId].yieldBonus;return{[id]:Math.max(1,n)};}
    const forgeMod=a=>{const quality=clamp(Math.floor(a.effectiveStrikes/2+(TEMPER[a.temperId]?.qualityBonus||0)+a.research*.25),0,3),factor=.65+quality*.3;return{pattern:a.patternId,quality,name:`${['粗成','稳成','精成','灵成'][quality]}${PATTERNS[a.patternId].name}`,stats:Object.fromEntries(Object.entries(PATTERNS[a.patternId].stats).map(([k,v])=>[k,k==='manaRegen'?Math.round(v*factor*100)/100:Math.round(v*factor)]))};};
    function brewingInfo(s){const a=s.workshop?.brew,at=station(s,'brew',a?.stationMapId),busy=!!a||!!s.alchemy;const recipes=Object.entries(BREWS).map(([id,b])=>{const r=CONTENT.RECIPES[id],reason=busy?'先完成当前丹炉。':at.reason||s.player.realm<b.realm&&'境界不足。'||!h.canPay(s,r.cost)&&'丹方基础材料不足。'||'';return{id,name:b.label,description:`目标炉温${b.target}度，稳定控火与纯净度共同影响实际药效。`,cost:copy(r.cost),baseOutput:copy(r.output),realmRequired:b.realm,targetTemperature:b.target,available:!reason,reason};});
      const catalysts=Object.values(CATALYSTS).map(c=>({...copy(c),available:h.canPay(s,c.cost),reason:h.canPay(s,c.cost)?'':'药引材料不足。'}));const controlReason=at.reason||!a&&'先投入丹方与药引。'||a.phase!=='extract'&&'当前阶段不能调火。'||'';
      const canPurify=!!a&&!controlReason&&a.purifyUses<4&&s.time-a.lastPurify>=2.5-1e-8&&s.player.mp>=8,sealChoices=[{id:'fast',label:'快凝',duration:3,description:'三秒成丹，最高精制；适合尽快补给。'},{id:'slow',label:'慢凝',duration:6,description:'六秒凝结，质量评分额外提高，可成上品。'}].map(c=>({...c,available:!!a&&a.phase==='condense'&&!at.reason,reason:at.reason||a?.phase!=='condense'&&'提炼完成后才能凝丹。'||''}));
      const remaining=a?(a.phase==='extract'?16-a.elapsed:a.phase==='sealing'?a.duration-a.elapsed:0):0;return{active:!!a,legacyBatch:!!s.alchemy,...at,phase:a?.phase||null,recipeId:a?.recipeId||null,recipe:a?recipes.find(r=>r.id===a.recipeId):null,catalystId:a?.catalystId||null,temperature:a?.temperature||20,targetTemperature:a?BREWS[a.recipeId].target:62,purity:a?.purity??0,stability:a?a.stable/Math.max(.001,a.phase==='extract'?a.elapsed:16):0,fire:a?.fire??1,elapsed:a?.elapsed||0,duration:a?.phase==='extract'?16:a?.duration||0,remaining,progress:a?a.phase==='ready'?1:a.elapsed/(a.phase==='extract'?16:a.duration||1):0,predictedQuality:a?QUALITY[brewQuality(a)]:'',qualityName:a?.phase==='ready'?QUALITY[brewQuality(a)]:'',output:a?.phase==='ready'?brewOutput(a):null,canClaim:!!a&&a.phase==='ready'&&!at.reason,claimReason:at.reason||a?.phase!=='ready'&&'丹药尚未完成。'||'',canPurify,purifyReason:controlReason||a?.purifyUses>=4&&'这一炉最多涤杂四次。'||a&&s.time-a.lastPurify<2.5-1e-8&&'调息后再涤杂。'||s.player.mp<8&&'需8灵力。'||'',recipes,catalysts,fireChoices:FIRE.map(c=>({...c,available:!controlReason,reason:controlReason})),sealChoices};}
    function forgingInfo(s){const a=s.workshop?.forge,at=station(s,'forge',a?.stationMapId),recipes=Object.values(CONTENT.RECIPES).filter(r=>Object.keys(r.output).some(id=>CONTENT.ITEMS[id]?.type==='equipment')).map(r=>{const reason=a?'先完成当前器物。':at.reason||s.player.realm<r.realmRequired&&'境界不足。'||!h.canPay(s,r.cost)&&'铸造材料不足。'||'';return{...copy(r),available:!reason,reason};});const controlReason=at.reason||!a&&'先选器物与刻纹开炉。'||a.phase!=='heat'&&'当前阶段不能调火锤炼。'||'';
      const temperChoices=Object.values(TEMPER).map(c=>{const reason=at.reason||a?.phase!=='temper'&&'锤炼完成后才能淬火。'||!h.canPay(s,c.cost)&&'淬火材料不足。'||'';return{...copy(c),available:!reason,reason};});const canHammer=!!a&&!controlReason&&a.strikes<6&&s.time-a.lastStrike>=.8-1e-8;
      return{active:!!a,...at,phase:a?.phase||null,recipeId:a?.recipeId||null,recipe:a?recipes.find(r=>r.id===a.recipeId):null,patternId:a?.patternId||null,temperature:a?.temperature||20,targetTemperature:74,fire:a?.fire??2,strikes:a?.strikes||0,effectiveStrikes:a?.effectiveStrikes||0,elapsed:a?.elapsed||0,duration:a?.phase==='heat'?8:a?.duration||0,remaining:a?(a.phase==='heat'?8-a.elapsed:a.phase==='quenching'?a.duration-a.elapsed:0):0,progress:a?a.phase==='ready'?1:a.elapsed/(a.phase==='heat'?8:a.duration||1):0,canHammer,hammerReason:controlReason||a?.strikes>=6&&'最多六锤。'||a&&s.time-a.lastStrike<.8-1e-8&&'等锤势回落后再锤。'||'',canClaim:!!a&&a.phase==='ready'&&!at.reason,claimReason:at.reason||a?.phase!=='ready'&&'器物尚未完成。'||'',output:a?.phase==='ready'?copy(CONTENT.RECIPES[a.recipeId].output):null,mod:a?forgeMod(a):null,recipes,patterns:Object.values(PATTERNS).map(copy),fireChoices:FIRE.map(c=>({...c,available:!controlReason,reason:controlReason})),temperChoices};}
    function workshopAction(s,id){const p=id.split(':'),kind=p[1],op=p[2],key=p[3],choice=p[4],w=s.workshop;
      if(kind==='brew'){const a=w.brew,info=brewingInfo(s);if(op==='start'&&p.length===5){const r=info.recipes.find(r=>r.id===key),c=CATALYSTS[choice],cost=r&&c&&merge(r.cost,c.cost);if(!r?.available||!c||!h.canPay(s,cost))return h.outcome(s,id,false,r?.reason||'丹方与药引材料不足。');h.pay(s,cost);w.brew={recipeId:key,catalystId:choice,stationMapId:s.mapId,phase:'extract',temperature:20,fire:1,purity:clamp(58+c.purityBonus,0,100),stable:0,elapsed:0,duration:16,purifyUses:0,lastPurify:s.time-2.5,startedAt:s.time,paidCost:cost,seal:null,research:w.research};return h.outcome(s,id,true,'灵材投入丹炉。调整炉火使温度保持在目标附近，必要时耗灵涤杂。');}
        if(op==='fire'&&p.length===4&&info.active&&info.phase==='extract'&&!info.reason&&FIRE.some(c=>c.id===key)){a.fire=Number(key);return h.outcome(s,id,true,'炉火已调整。');}
        if(op==='purify'&&p.length===3){if(!info.canPurify)return h.outcome(s,id,false,info.purifyReason);s.player.mp-=8;a.purity=Math.min(100,a.purity+12);a.purifyUses++;a.lastPurify=s.time;return h.outcome(s,id,true,'耗8灵力涤去丹炉杂气。');}
        if(op==='seal'&&p.length===4){const c=info.sealChoices.find(c=>c.id===key);if(!c?.available)return h.outcome(s,id,false,c?.reason||'未知凝丹法。');a.seal=key;a.phase='sealing';a.elapsed=0;a.duration=c.duration;return h.outcome(s,id,true,'丹性已定，开始凝丹。');}
        if(op==='claim'&&p.length===3){if(!info.canClaim)return h.outcome(s,id,false,info.claimReason);h.grant(s,info.output);w.brew=null;return h.outcome(s,id,true,`${info.qualityName}丹成，药物已收入行囊。`);}
      }else if(kind==='forge'){const a=w.forge,info=forgingInfo(s);if(op==='start'&&p.length===5){const r=info.recipes.find(r=>r.id===key);if(!r?.available||!PATTERNS[choice])return h.outcome(s,id,false,r?.reason||'未识此器物刻纹。');h.pay(s,r.cost);w.forge={recipeId:key,patternId:choice,stationMapId:s.mapId,phase:'heat',temperature:20,fire:2,elapsed:0,duration:8,strikes:0,effectiveStrikes:0,lastStrike:s.time-.8,startedAt:s.time,paidCost:copy(r.cost),temperId:null,research:w.research};return h.outcome(s,id,true,'器胚入炉，适温锤炼后选择淬火。');}
        if(op==='fire'&&p.length===4&&a?.phase==='heat'&&!info.reason&&FIRE.some(c=>c.id===key)){a.fire=Number(key);return h.outcome(s,id,true,'铸炉火候已调整。');}
        if(op==='hammer'&&p.length===3){if(!info.canHammer)return h.outcome(s,id,false,info.hammerReason);const proper=Math.abs(a.temperature-74)<=12+a.research*2;a.strikes++;a.effectiveStrikes+=proper?1:.25;a.lastStrike=s.time;h.effect(s,'particle',s.player.x,s.player.y-20,.35,18,{color:proper?'#ffe6a2':'#bb9471'});return h.outcome(s,id,true,proper?'炉温适宜，这一锤凝成器纹。':'炉温偏离，这一锤只有少量效果。');}
        if(op==='temper'&&p.length===4){const c=info.temperChoices.find(c=>c.id===key);if(!c?.available)return h.outcome(s,id,false,c?.reason||'未知淬火法。');h.pay(s,c.cost);a.paidCost=merge(a.paidCost,c.cost);a.temperId=key;a.phase='quenching';a.elapsed=0;a.duration=c.duration;return h.outcome(s,id,true,'器纹定形，开始淬火。');}
        if(op==='claim'&&p.length===3){if(!info.canClaim)return h.outcome(s,id,false,info.claimReason);const old=h.stats(s),item=Object.keys(info.output)[0];h.grant(s,info.output);w.mods[item]=info.mod;w.forge=null;const now=h.stats(s);s.player.hp=clamp(s.player.hp/old.maxHp*now.maxHp,0,now.maxHp);s.player.mp=clamp(s.player.mp/old.maxMp*now.maxMp,0,now.maxMp);return h.outcome(s,id,true,`${CONTENT.ITEMS[item].name}完成，刻入${info.mod.name}。同型号旧刻纹已覆盖。`);}
      }
      return h.outcome(s,id,false,'当前阶段不能进行此工坊操作。');
    }
    function plan(s,id,recipeId){const m=s.management,v=m.facilities[id],base=s.sect.facilities[id],r=ORDERS[recipeId],worker=m.workers[base.discipleId],policy=POLICIES[worker?.policy||'balanced'],pos=POSITIONS.find(p=>p.id===v.position),sources=[];let multiplier=policy.speed*(1+Math.max(0,base.level-1)*.25)*(1-(worker?.fatigue||0)/200);
      sources.push(`${policy.name} ×${policy.speed.toFixed(2)}`);if(pos.element===r.element){multiplier*=1.2;sources.push('地脉与产线相契 ×1.20');}
      const ix=POSITIONS.findIndex(p=>p.id===v.position),upstream=POSITIONS[(ix+4)%5],otherId=Object.keys(m.facilities).find(k=>k!==id&&m.facilities[k].position===upstream.id);if(otherId){const o=m.facilities[otherId],f=s.sect.facilities[otherId],or=ORDERS[o.batch?.recipeId||o.order?.recipeId];if(f.level>0&&f.discipleId&&or&&GENERATES[or.element]===r.element){multiplier*=1.12;sources.push(`${CONTENT.SECT_FACILITIES[otherId].name}上游相生 ×1.12`);}}
      const disciple=CONTENT.SECT_DISCIPLES[base.discipleId];if(disciple?.element===r.element){multiplier*=1.15;sources.push(`${disciple.name}灵根专长 ×1.15`);}const relation=h.relationshipBonus?clamp(h.relationshipBonus(s,base.discipleId)||1,1,1.5):1;if(relation>1){multiplier*=relation;sources.push(`人物协作 ×${relation.toFixed(2)}`);}const trait=h.traitProductionBonus?clamp(h.traitProductionBonus(s,base.discipleId)||1,.5,2):1;if(trait!==1){multiplier*=trait;sources.push(`弟子词条 ×${trait.toFixed(2)}`);}if(worker?.fatigue>0)sources.push(`疲劳效率 ${Math.round((1-worker.fatigue/200)*100)}%`);
      return{duration:r.duration/Math.max(.2,multiplier),multiplier,sources,cost:merge(r.cost,policy.extraCost),reward:Object.fromEntries(Object.entries(r.reward).map(([k,n])=>[k,n*(k==='research'?1:Math.max(1,base.level))]))};}
    const researchRoom=(s,v)=>Math.max(0,3-s.workshop.research-(v.batch?.recipeId==='research'?1:0)-v.stored.filter(b=>b.recipeId==='research').length);
    function managementInfo(s){const m=s.management,reason=h.sectReason(s),legacy=Object.values(s.sect.facilities).some(f=>f.stored>0),enableReason=reason||s.player.realm<1&&'筑基后可调度生产。'||m.enabled&&'已经开启生产调度。'||legacy&&'请先领取旧设施积存成果。'||'';
      const facilities=Object.entries(m.facilities).map(([id,v])=>{const f=s.sect.facilities[id],r=ORDERS[v.batch?.recipeId||v.order?.recipeId||({garden:'herbs',forge:'iron',library:'insight'}[id])],p=plan(s,id,r.id),worker=m.workers[f.discipleId],busy=!!v.batch,recipes=Object.values(ORDERS).filter(r=>r.facility===id).map(r=>{const preview=plan(s,id,r.id),why=reason||!m.enabled&&'先开启生产调度。'||f.level<1&&'先建设此设施。'||r.id==='research'&&researchRoom(s,v)===0&&'三级工艺已完成或正在研习，先领取成果。'||'';return{...copy(r),cost:preview.cost,reward:preview.reward,duration:preview.duration,maxQuantity:r.id==='research'?researchRoom(s,v):6,available:!why,reason:why};});
        const totalRewards=merge(...v.stored.map(b=>b.reward));return{id,name:CONTENT.SECT_FACILITIES[id].name,level:f.level,position:v.position,discipleId:f.discipleId,order:copy(v.order),batch:copy(v.batch),stored:v.stored.length,storedRewards:copy(v.stored),totalRewards,capacity:3,recipes,duration:v.batch?.duration||p.duration,multiplier:p.multiplier,nextDuration:p.duration,nextMultiplier:p.multiplier,batchMultiplier:v.batch?ORDERS[v.batch.recipeId].duration/v.batch.duration:null,sources:p.sources,workerFatigue:worker?.fatigue||0,resting:!!worker?.resting,producing:m.enabled&&!!v.batch&&!!f.discipleId&&!worker?.resting,canClaim:m.enabled&&!reason&&v.stored.length>0,claimReason:reason||!v.stored.length&&'暂无已完成批次。'||'',canMove:m.enabled&&!reason&&!busy,moveReason:reason||busy&&'先完成已经投入材料的批次。'||'',waitingReason:!f.discipleId?'未派驻弟子。':worker?.resting?'弟子正在轮休。':v.stored.length>=3?'仓库已满，领取后继续。':!v.order?.quantity&&!v.batch?'未排生产订单。':!v.batch&&!h.canPay(s,p.cost)?'下一批投入材料不足。':''};});
      const workers=Object.entries(m.workers).map(([id,w])=>({...copy(w),id,name:CONTENT.SECT_DISCIPLES[id].name,recruited:!!s.sect.disciples[id]?.recruited,assignedTo:Object.keys(s.sect.facilities).find(f=>s.sect.facilities[f].discipleId===id)||null}));return{enabled:m.enabled,inSect:s.mapId==='sect'&&!s.activity,canEnable:!enableReason,reason:enableReason,research:s.workshop.research,positions:copy(POSITIONS),policies:Object.values(POLICIES).map(copy),facilities,workers};}
    function managementAction(s,id){const p=id.split(':'),op=p[1],key=p[2],choice=p[3],m=s.management,why=h.sectReason(s);if(why)return h.outcome(s,id,false,why);if(op==='enable'&&p.length===2){const info=managementInfo(s);if(!info.canEnable)return h.outcome(s,id,false,info.reason);const used=new Set();for(const[fid,v]of Object.entries(m.facilities)){const f=s.sect.facilities[fid],old=h.facilityInfo(s,fid);v.position=!used.has(f.position)?f.position:POSITIONS.find(p=>!used.has(p.id)).id;used.add(v.position);f.position=v.position;v.carry=clamp(f.progress/Math.max(1,old.duration),0,.999);f.progress=0;if(v.carry>0)v.order={recipeId:{garden:'herbs',forge:'iron',library:'insight'}[fid],quantity:1};}m.enabled=true;return h.outcome(s,id,true,'生产调度已开启。原未完成进度承接到首批订单；之后每批投入材料，弟子按轮值生产。');}
      if(!m.enabled)return h.outcome(s,id,false,'先开启生产调度。');
      if(op==='position'&&p.length===4){const v=entry(m.facilities,key),position=POSITIONS.find(p=>p.id===choice),info=managementInfo(s).facilities.find(f=>f.id===key);if(!v||!position||!info.canMove)return h.outcome(s,id,false,info?.moveReason||'未知设施或方位。');if(Object.entries(m.facilities).some(([fid,f])=>fid!==key&&f.position===choice))return h.outcome(s,id,false,'此方位已有设施，先腾出空位。');v.position=choice;s.sect.facilities[key].position=choice;return h.outcome(s,id,true,'设施已迁入新方位，后续批次按新地脉结算。');}
      if(op==='order'&&p.length===5){const v=entry(m.facilities,key),recipe=ORDERS[choice],quantity=Number(p[4]),info=managementInfo(s).facilities.find(f=>f.id===key)?.recipes.find(r=>r.id===choice);if(!v||!recipe||!Number.isInteger(quantity)||quantity<1||quantity>6||!info?.available)return h.outcome(s,id,false,info?.reason||'订单需为本设施配方、1至6批。');if(quantity>info.maxQuantity)return h.outcome(s,id,false,`工艺最多三级，还能排入${info.maxQuantity}批研究；已有在制与积存已计入。`);v.order={recipeId:choice,quantity};return h.outcome(s,id,true,'后续订单已排入；在制批次保持，材料在每批开工时扣除。');}
      if(op==='cancel'&&p.length===3){const v=entry(m.facilities,key);if(!v)return h.outcome(s,id,false,'未知设施。');v.order=null;return h.outcome(s,id,true,'未开工订单已撤下，已付材料的在制批次继续。');}
      if(op==='claim'&&p.length===3){const v=entry(m.facilities,key);if(!v||!v.stored.length)return h.outcome(s,id,false,'暂无已完成批次。');const reward=merge(...v.stored.map(b=>b.reward)),research=reward.research||0;delete reward.research;h.grant(s,reward);s.workshop.research=Math.min(3,s.workshop.research+research);v.stored=[];return h.outcome(s,id,true,'生产成果已领取，工艺成果计入研究，仓库腾出后继续。');}
      if(op==='policy'&&p.length===4){const worker=entry(m.workers,key),policy=POLICIES[choice],fid=Object.keys(s.sect.facilities).find(fid=>s.sect.facilities[fid].discipleId===key);if(!worker||!policy||!s.sect.disciples[key]?.recruited)return h.outcome(s,id,false,'弟子尚未招募或轮值未知。');if(fid&&m.facilities[fid].batch)return h.outcome(s,id,false,'当前批次已按轮值付料，完成后再更换政策。');worker.policy=choice;return h.outcome(s,id,true,`${CONTENT.SECT_DISCIPLES[key].name}改为${policy.name}。`);}
      if(op==='rest'&&p.length===3){const worker=entry(m.workers,key);if(!worker||!s.sect.disciples[key]?.recruited)return h.outcome(s,id,false,'弟子尚未招募。');worker.resting=true;worker.restRemaining=8;return h.outcome(s,id,true,'弟子开始轮休，至少8秒，已有在制进度保留。');}
      return h.outcome(s,id,false,'未知生产调度。');
    }
    function managementStep(s,dt){const m=s.management;if(!m.enabled||!s.sect.joined)return;for(const[id,w]of Object.entries(m.workers)){if(!s.sect.disciples[id]?.recruited)continue;const assigned=Object.values(s.sect.facilities).some(f=>f.discipleId===id);if(w.resting){w.fatigue=Math.max(0,w.fatigue-dt*4);w.restRemaining=Math.max(0,(w.restRemaining||0)-dt);if(w.fatigue<=POLICIES[w.policy].recoverTo&&w.restRemaining<=0)w.resting=false;}else if(!assigned)w.fatigue=Math.max(0,w.fatigue-dt*2);}
      for(const[id,v]of Object.entries(m.facilities)){const f=s.sect.facilities[id],w=m.workers[f.discipleId];if(!f.level||!w||!s.sect.disciples[f.discipleId]?.recruited||v.stored.length>=3||w.resting)continue;const policy=POLICIES[w.policy];if(w.fatigue>=policy.threshold){w.resting=true;w.restRemaining=8;continue;}
        if(!v.batch&&v.order?.quantity){const r=ORDERS[v.order.recipeId];if(r.id==='research'&&s.workshop.research>=3){v.order=null;continue;}const p=plan(s,id,r.id);if(!h.canPay(s,p.cost))continue;h.pay(s,p.cost);v.batch={recipeId:r.id,level:f.level,workerId:f.discipleId,policy:w.policy,progress:v.carry*p.duration,duration:p.duration,cost:p.cost,reward:p.reward,startedAt:s.time};v.carry=0;v.order.quantity--;if(v.order.quantity===0)v.order=null;}
        if(!v.batch)continue;v.batch.progress=Math.min(v.batch.duration,v.batch.progress+dt);w.fatigue=Math.min(100,w.fatigue+dt*POLICIES[v.batch.policy].fatigue*(h.traitFatigueBonus?clamp(h.traitFatigueBonus(s,f.discipleId)||1,.25,2):1));if(v.batch.progress>=v.batch.duration-1e-8){v.batch.progress=v.batch.duration;v.stored.push(v.batch);v.batch=null;h.log(s,`${CONTENT.SECT_FACILITIES[id].name}一批生产完成，等待领取。`);}
      }
    }
    function validate(raw,s,version){if(version<6){init(s);return;}const fail=()=>{throw Error('Invalid workshop or management save');},obj=(x,keys)=>{if(!x||typeof x!=='object'||Array.isArray(x)||keys&&Object.keys(x).some(k=>!keys.includes(k)))fail();return x;},num=(x,a,b,integer=false)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<a-1e-7||x>b+1e-7||integer&&!Number.isInteger(x))fail();return x;},bool=x=>{if(typeof x!=='boolean')fail();return x;};
      const w=obj(raw.workshop,['brew','forge','mods','medicineBuffs','research']),m=obj(raw.management,['enabled','facilities','workers']);num(w.research,0,3,true);obj(w.mods);obj(w.medicineBuffs,['rage','ward','insight']);for(const[id,v]of Object.entries(w.mods)){if(!Object.hasOwn(CONTENT.ITEMS,id)||CONTENT.ITEMS[id].type!=='equipment'||!(s.inventory[id]>0))fail();obj(v,['pattern','quality','name','stats']);if(!PATTERNS[v.pattern])fail();num(v.quality,0,3,true);const expected=forgeMod({patternId:v.pattern,effectiveStrikes:v.quality*2,temperId:'water',research:0});if(v.name!==expected.name||!same(obj(v.stats),expected.stats))fail();}
      for(const[type,b]of Object.entries(w.medicineBuffs)){obj(b,['itemId','potency','life']);const drug=MEDICINES[b.itemId];if(!drug||drug.medicineEffect!==type||b.potency!==drug.potency)fail();num(b.life,0,drug.duration);if(b.life<=0)fail();}
      const checkStation=a=>{if(!['main','red','snow','sect'].includes(a.stationMapId)||!s.progress.visited.includes(a.stationMapId))fail();num(a.startedAt,0,s.time);num(a.research,0,w.research,true);num(a.temperature,0,130);num(a.fire,0,3,true);obj(a.paidCost);};
      if(w.brew!==null){const a=obj(w.brew,['recipeId','catalystId','stationMapId','phase','temperature','fire','purity','stable','elapsed','duration','purifyUses','lastPurify','startedAt','paidCost','seal','research']);if(!BREWS[a.recipeId]||!CATALYSTS[a.catalystId]||s.player.realm<BREWS[a.recipeId].realm||!['extract','condense','sealing','ready'].includes(a.phase)||s.alchemy)fail();checkStation(a);if(!same(a.paidCost,merge(CONTENT.RECIPES[a.recipeId].cost,CATALYSTS[a.catalystId].cost)))fail();num(a.purity,0,100);num(a.stable,0,a.phase==='extract'?a.elapsed:16);num(a.purifyUses,0,4,true);num(a.lastPurify,a.startedAt-2.5,s.time);if(!a.purifyUses&&Math.abs(a.lastPurify-(a.startedAt-2.5))>1e-6||a.purifyUses&&(a.lastPurify<a.startedAt+(a.purifyUses-1)*2.5-1e-6))fail();if(['extract','condense'].includes(a.phase)){if(a.seal!==null||a.duration!==16)fail();num(a.elapsed,0,16);if(a.phase==='condense'&&a.elapsed!==16||a.phase==='extract'&&a.elapsed>=16)fail();}else{if(!['fast','slow'].includes(a.seal)||a.duration!==(a.seal==='fast'?3:6))fail();num(a.elapsed,0,a.duration);if(a.phase==='ready'&&a.elapsed!==a.duration||a.phase==='sealing'&&a.elapsed>=a.duration)fail();}const totalElapsed=['sealing','ready'].includes(a.phase)?16+a.elapsed:a.elapsed;if(totalElapsed>s.time-a.startedAt+1e-6)fail();}
      if(w.forge!==null){const a=obj(w.forge,['recipeId','patternId','stationMapId','phase','temperature','fire','elapsed','duration','strikes','effectiveStrikes','lastStrike','startedAt','paidCost','temperId','research']),r=CONTENT.RECIPES[a.recipeId];if(!r||!Object.keys(r.output).every(id=>CONTENT.ITEMS[id]?.type==='equipment')||!PATTERNS[a.patternId]||s.player.realm<r.realmRequired||!['heat','temper','quenching','ready'].includes(a.phase))fail();checkStation(a);num(a.strikes,0,6,true);num(a.effectiveStrikes,.25*a.strikes,a.strikes);const properStrikes=(a.effectiveStrikes-.25*a.strikes)/.75;if(!Number.isInteger(properStrikes)||properStrikes>a.strikes)fail();num(a.lastStrike,a.startedAt-.8,s.time);if(!a.strikes&&Math.abs(a.lastStrike-(a.startedAt-.8))>1e-6||a.strikes&&(a.lastStrike<a.startedAt+(a.strikes-1)*.8-1e-6))fail();if(['heat','temper'].includes(a.phase)){if(a.temperId!==null||a.duration!==8||!same(a.paidCost,r.cost))fail();num(a.elapsed,0,8);if(a.phase==='temper'&&a.elapsed!==8||a.phase==='heat'&&a.elapsed>=8)fail();}else{const t=TEMPER[a.temperId];if(!t||a.duration!==t.duration||!same(a.paidCost,merge(r.cost,t.cost)))fail();num(a.elapsed,0,a.duration);if(a.phase==='ready'&&a.elapsed!==a.duration||a.phase==='quenching'&&a.elapsed>=a.duration)fail();}const totalElapsed=['quenching','ready'].includes(a.phase)?8+a.elapsed:a.elapsed;if(totalElapsed>s.time-a.startedAt+1e-6)fail();}
      bool(m.enabled);obj(m.facilities,Object.keys(CONTENT.SECT_FACILITIES));obj(m.workers,Object.keys(CONTENT.SECT_DISCIPLES));if(Object.keys(m.facilities).length!==3||Object.keys(m.workers).length!==3||m.enabled&&(!s.sect.joined||s.player.realm<1))fail();const occupied=new Set();
      for(const[id,v]of Object.entries(m.workers)){obj(v,['fatigue','policy','resting','restRemaining']);num(v.fatigue,0,100);if(!POLICIES[v.policy])fail();bool(v.resting);if(v.restRemaining!==undefined)num(v.restRemaining,0,8);if(!s.sect.disciples[id]?.recruited&&(v.fatigue!==0||v.resting||v.policy!=='balanced'))fail();}
      for(const[id,v]of Object.entries(m.facilities)){obj(v,['position','order','batch','stored','carry']);if(!POSITIONS.some(p=>p.id===v.position)||occupied.has(v.position))fail();occupied.add(v.position);num(v.carry,0,.999);if(m.enabled&&s.sect.facilities[id].position!==v.position)fail();if(v.order!==null){obj(v.order,['recipeId','quantity']);if(ORDERS[v.order.recipeId]?.facility!==id||s.sect.facilities[id].level<1)fail();num(v.order.quantity,1,6,true);}if(!Array.isArray(v.stored)||v.stored.length>3)fail();const batches=[...v.stored,...v.batch?[v.batch]:[]];for(const b of batches){obj(b,['recipeId','level','workerId','policy','progress','duration','cost','reward','startedAt']);const r=ORDERS[b.recipeId],policy=POLICIES[b.policy];if(r?.facility!==id||!policy||!Object.hasOwn(m.workers,b.workerId)||!s.sect.disciples[b.workerId]?.recruited)fail();num(b.level,1,s.sect.facilities[id].level,true);num(b.duration,1,180);num(b.progress,0,b.duration);num(b.startedAt,0,s.time);const cost=merge(r.cost,policy.extraCost),reward=Object.fromEntries(Object.entries(r.reward).map(([k,n])=>[k,n*(k==='research'?1:b.level)]));if(!same(obj(b.cost),cost)||!same(obj(b.reward),reward))fail();if(v.stored.includes(b)&&b.progress!==b.duration||b===v.batch&&b.progress>=b.duration)fail();}if(!m.enabled&&(v.order!==null||v.batch!==null||v.stored.length||v.carry!==0))fail();}
      const researchLine=m.facilities.library,researchPending=(researchLine.batch?.recipeId==='research'?1:0)+researchLine.stored.filter(b=>b.recipeId==='research').length+(researchLine.order?.recipeId==='research'?researchLine.order.quantity:0);if(w.research+researchPending>3)fail();
      s.workshop=copy(w);s.management=copy(m);
    }
    function bonuses(s){const out={stats:{},attackMultiplier:1};for(const item of Object.values(s.equipment||{})){const m=s.workshop?.mods[item];if(m)for(const[k,v]of Object.entries(m.stats))out.stats[k]=(out.stats[k]||0)+v;}const r=s.workshop?.medicineBuffs.rage;if(r)out.attackMultiplier=(1+r.potency)/((s.buffs||[]).some(b=>b.type==='rage')?1.25:1);return out;}
    const incomingMultiplier=s=>{const b=s.workshop?.medicineBuffs.ward;return b?(1-b.potency)/((s.buffs||[]).some(b=>b.type==='ward')?.75:1):1;};
    const cultivationMultiplier=s=>{const b=s.workshop?.medicineBuffs.insight;return b?(1+b.potency)/((s.buffs||[]).some(b=>b.type==='insight')?1.3:1):1;};
    function medicineAction(s,id){const item=MEDICINES[id.split(':')[1]];if(!item)return null;if(s.dead||!(s.inventory[item.id]>0))return h.outcome(s,id,false,s.dead?'先重聚灵身。':'没有此丹药。');const st=h.stats(s);if(item.medicineEffect==='healing'&&s.player.hp>=st.maxHp&&s.player.mp>=st.maxMp||item.medicineEffect==='mana'&&s.player.mp>=st.maxMp)return h.outcome(s,id,false,'当前无需服用。');s.inventory[item.id]--;
      if(item.medicineEffect==='healing'){s.player.hp=Math.min(st.maxHp,s.player.hp+st.maxHp*item.potency);s.player.mp=Math.min(st.maxMp,s.player.mp+st.maxMp*(item.quality===1?.35:.45));}else if(item.medicineEffect==='mana')s.player.mp=Math.min(st.maxMp,s.player.mp+st.maxMp*item.potency);else{const old=s.workshop.medicineBuffs[item.medicineEffect],stronger=old&&old.potency>item.potency;s.workshop.medicineBuffs[item.medicineEffect]={itemId:stronger?old.itemId:item.id,potency:Math.max(old?.potency||0,item.potency),life:Math.max(old?.life||0,item.duration)};}return h.outcome(s,id,true,`已服用${item.name}，药力真实生效。`);}
    function step(s,dt){if(s.dead||!(dt>0))return;for(const[k,b]of Object.entries(s.workshop.medicineBuffs)){b.life-=dt;if(b.life<=0)delete s.workshop.medicineBuffs[k];}
      const a=s.workshop.brew;if(a?.phase==='extract'){a.temperature=clamp(a.temperature+(FIRE[a.fire].target+CATALYSTS[a.catalystId].heatOffset-a.temperature)*.6*dt,0,130);a.elapsed=Math.min(16,a.elapsed+dt);const delta=Math.abs(a.temperature-BREWS[a.recipeId].target);if(delta<=12+a.research*2)a.stable=Math.min(16,a.stable+dt);a.purity=clamp(a.purity+(delta<8?.5:delta>22?-1.4:-.1)*dt,0,100);if(a.elapsed>=16-1e-8){a.elapsed=16;a.phase='condense';h.log(s,'提炼完成，选择快凝或慢凝。');}}else if(a?.phase==='sealing'){a.elapsed=Math.min(a.duration,a.elapsed+dt);if(a.elapsed>=a.duration-1e-8){a.elapsed=a.duration;a.phase='ready';h.log(s,'丹炉成丹，可回原炉收丹。');}}
      const f=s.workshop.forge;if(f?.phase==='heat'){f.temperature=clamp(f.temperature+(FIRE[f.fire].target-f.temperature)*.7*dt,0,130);f.elapsed=Math.min(8,f.elapsed+dt);if(f.elapsed>=8-1e-8){f.elapsed=8;f.phase='temper';h.log(s,'锤炼完成，请选择淬火。');}}else if(f?.phase==='quenching'){f.elapsed=Math.min(f.duration,f.elapsed+dt);if(f.elapsed>=f.duration-1e-8){f.elapsed=f.duration;f.phase='ready';h.log(s,'器物淬火完成，可回原铸台领取。');}}
      managementStep(s,dt);
    }
    function action(s,id){if(typeof id!=='string')return null;if(id.startsWith('workshop:'))return workshopAction(s,id);if(id.startsWith('management:'))return managementAction(s,id);if(id.startsWith('use:')&&id.split(':').length===2)return medicineAction(s,id);return null;}
    function info(s){return{brewing:brewingInfo(s),forging:forgingInfo(s),management:managementInfo(s),research:s.workshop.research,mods:copy(s.workshop.mods),medicineBuffs:copy(s.workshop.medicineBuffs),medicines:Object.values(MEDICINES).map(copy)};}
    return{init,validate,action,step,info,brewingInfo,forgingInfo,managementInfo,bonuses,incomingMultiplier,cultivationMultiplier};
  };
});
