/* Persistent frontier quests, adult relationships, talents and disciple temperaments. */
(function(root,factory){'use strict';const make=factory();if(typeof module==='object'&&module.exports)module.exports=make;if(root)root.XianWorldlife=make;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';const copy=x=>JSON.parse(JSON.stringify(x)),own=(o,k)=>Object.hasOwn(o,k);
  return function createWorldlife(C,h){
    function init(s){s.worldlife={schema:1,met:[],quests:{},kills:{},visits:{},talents:[],relations:{},partner:null,companion:null,companionCd:0,thief:null,discipleTraits:{},stolen:{},poison:{life:0,damage:0,tick:0}};}
    function effects(s){const out={maxHp:0,maxMp:0,attack:0,defense:0,speed:0,manaRegen:0,incoming:1,xp:1,spellMana:1,fireDamage:1,iceDamage:1,gather:1,production:1,fatigue:1,companionCooldown:12};for(const id of s.worldlife?.talents||[])for(const[k,v]of Object.entries(C.TALENTS[id].effects)){if(['incoming','xp','spellMana','fireDamage','iceDamage','gather','production','fatigue'].includes(k))out[k]*=v;else if(k==='companionCooldown')out[k]=v;else out[k]+=v;}return out;}
    function activeTrait(s,id){return C.DISCIPLE_TRAITS[s.worldlife?.discipleTraits[id]||C.DISCIPLE_INNATE[id]];}
    function bonuses(s){const e=effects(s),out={};for(const k of ['maxHp','maxMp','attack','defense','speed','manaRegen'])out[k]=e[k];if(s.management?.enabled)for(const id of Object.keys(C.SECT_DISCIPLES))if(s.sect.disciples[id].recruited){const trait=activeTrait(s,id);if(trait?.id==='idle'&&(s.management.workers[id]?.fatigue||0)>=50)continue;for(const[k,v]of Object.entries(trait?.stats||{}))out[k]=(out[k]||0)+v;}return out;}
    function productionBonus(s,id){return s.management?.enabled?effects(s).production*(activeTrait(s,id)?.production||1):1;}
    function fatigueBonus(s,id){return s.management?.enabled?effects(s).fatigue*(activeTrait(s,id)?.fatigue||1):1;}
    function npcReason(s,n){const location=!s.activity&&!s.journey?.active&&h.mapInfo(s).npcs.find(v=>v.id===n.id);return s.dead?'先重聚灵身。':!location||h.distance(s.player,location)>105?`请靠近${n.name}。`:!h.isSafe(s)?'请回到安全街区交谈。':'';}
    function measure(s,q){if(q.kind==='kill')return s.worldlife.kills[q.enemyType]||0;if(q.kind==='gather')return s.progress.gathered[q.resource]||0;if(q.kind==='visit')return s.worldlife.visits[q.targetMap]||0;return s.player[q.item]||s.inventory[q.item]||0;}
    function worldQuestInfo(s){return Object.values(C.WORLD_QUESTS).map(q=>{const r=s.worldlife.quests[q.id],accepted=!!r,claimed=!!r?.claimedAt||r?.claimedAt===0,met=s.worldlife.met.includes(q.npcId),common=npcReason(s,C.WORLD_NPCS[q.npcId]),missing=q.prerequisites.find(id=>s.worldlife.quests[id]?.claimedAt==null),progress=r?Math.max(0,q.kind==='delivery'?measure(s,q):measure(s,q)-r.baseline):0,acceptReason=common||!met&&'先与人物会面。'||accepted&&'已接取此支线。'||missing&&'先完成前置支线。'||'',claimReason=common||!accepted&&'尚未接取。'||claimed&&'奖励已领取。'||progress<q.target&&'目标尚未完成。'||q.cost&&!h.canPay(s,q.cost)&&'交付材料不足。'||'';return{...q,progress:Math.min(progress,q.target),accepted,claimed,canAccept:!acceptReason,canClaim:!claimReason,reason:claimed?'支线已完成。':accepted?claimReason:acceptReason};});}
    const claimedCount=s=>Object.values(s.worldlife.quests).filter(q=>q.claimedAt!=null).length;
    function talentInfo(s){const pointsEarned=1+s.player.realm+Math.floor(claimedCount(s)/3),pointsSpent=s.worldlife.talents.reduce((n,id)=>n+C.TALENTS[id].cost,0),pointsAvailable=pointsEarned-pointsSpent;return{pointsEarned,pointsSpent,pointsAvailable,entries:Object.values(C.TALENTS).map(t=>{const unlocked=s.worldlife.talents.includes(t.id),reason=unlocked?'已领悟。':s.dead?'先重聚灵身。':!h.isSafe(s)?'请回安全据点领悟。':s.player.realm<t.realmRequired?'境界不足。':t.prerequisites.some(id=>!s.worldlife.talents.includes(id))?'先领悟前置天赋。':pointsAvailable<t.cost?'天赋点不足；每次破境、每完成三条新支线增加一点。':'';return{...t,unlocked,available:!reason,reason};})};}
    function romanceInfo(s,n){if(!n.romance)return null;const r=s.worldlife.relations[n.id]||{gifts:0},met=s.worldlife.met.includes(n.id),quests=Object.values(C.WORLD_QUESTS).filter(q=>q.npcId===n.id),done=quests.filter(q=>s.worldlife.quests[q.id]?.claimedAt!=null).length,affinity=(met?1:0)+done*2+r.gifts,common=npcReason(s,n),giftReason=common||!met&&'先相识。'||r.gifts>=3&&'她更重视共同经历，三次赠礼已经足够。'||!h.canPay(s,n.giftCost)&&'赠礼材料不足。'||'',bondCost={stones:80,core:2},bondReason=common||!met&&'尚未相识。'||s.worldlife.partner&&'已有相互承诺的道侣。'||done<quests.length&&'先完成她的两段同行支线。'||affinity<6&&'好感需要六点。'||!h.canPay(s,bondCost)&&'合契材料不足。'||'',bonded=s.worldlife.partner===n.id,travelReason=common||!bonded&&'先与她互许道侣之约。'||'';return{adult:true,candidate:true,age:n.age,affinity,gifts:r.gifts,bonded,partnerId:s.worldlife.partner,canGift:!giftReason,giftCost:copy(n.giftCost),giftReason,canBond:!bondReason,bondCost,bondReason,canTravel:!travelReason,travelReason,accompanying:s.worldlife.companion===n.id,description:n.companionEffect==='heal'?'共同历练时，每12秒恢复5%气血；已满则不消耗护持。':'共同历练时，每12秒恢复8%灵力；已满则不消耗护持。'};}
    function thiefInfo(s,n){if(n.id!=='emptyHand')return null;const done=['thiefDebts','thiefRepay'].every(id=>s.worldlife.quests[id]?.claimedAt!=null),choices=[{id:'mercy',label:'让他偿债改过',cost:{stones:20},reward:{xp:130,spiritwood:4},description:'再垫20灵石，换来灵木与修为；解锁弟子重情重义训导。'},{id:'justice',label:'交由城卫裁决',cost:{},reward:{stones:45,iron:4},description:'城卫发还45灵石并奖励玄铁；解锁弟子一丝不苟训导。'}],reason=npcReason(s,n)||s.worldlife.thief&&'处置已作出，不能重复领取。'||!done&&'先帮他追缴钱袋并缴清赔偿押金。'||'';return{resolved:!!s.worldlife.thief,choice:s.worldlife.thief,canResolve:!reason,reason,choices:choices.map(c=>({...c,available:!reason&&h.canPay(s,c.cost),reason:reason||!h.canPay(s,c.cost)&&'灵石不足。'||''}))};}
    function worldNpcInfo(s,id){const n=C.WORLD_NPCS[id];if(!n)return null;const reason=npcReason(s,n),met=s.worldlife.met.includes(id);return{...n,near:!reason,reason,met,talkAvailable:!reason&&!met,quests:worldQuestInfo(s).filter(q=>q.npcId===id),romance:romanceInfo(s,n),affinity:romanceInfo(s,n)?.affinity||0,thief:thiefInfo(s,n)};}
    function discipleTraitInfo(s){return Object.values(C.SECT_DISCIPLES).map(d=>{const trait=activeTrait(s,d.id),recruited=s.sect.disciples[d.id].recruited,common=s.dead?'先重聚灵身。':!h.isSafe(s)||s.mapId!=='sect'?'请回青云宗训导。':!recruited?'先招募这名弟子。':!s.management?.enabled?'先在宗门启用生产调度，性情才影响排班。':'';return{id:d.id,name:d.name,recruited,traits:[copy(trait)],active:!!s.management?.enabled&&recruited,productionMultiplier:productionBonus(s,d.id),fatigueMultiplier:fatigueBonus(s,d.id),battleDescription:trait.description,trainOptions:Object.values(C.DISCIPLE_TRAITS).map(t=>{const cost={stones:45,essence:1},reason=common||t.id===trait.id&&'已有此性情。'||t.id==='loyal'&&s.worldlife.thief!=='mercy'&&'先选择让空空儿偿债改过。'||t.id==='careful'&&s.worldlife.thief!=='justice'&&'先选择让城卫裁决空空儿。'||!h.canPay(s,cost)&&'训导材料不足。'||'';return{...t,cost,available:!reason,reason};})};});}
    function action(s,id){if(typeof id!=='string'||!id.startsWith('worldlife:'))return null;const p=id.split(':'),w=s.worldlife,bad=message=>h.outcome(s,id,false,message),ok=message=>h.outcome(s,id,true,message);
      if(p[1]==='npc'&&p[2]==='talk'&&p.length===4){const n=worldNpcInfo(s,p[3]);if(!n||!n.talkAvailable)return bad(n?.reason||'已经相识，或此处没有这位人物。');w.met.push(n.id);if(n.romance)w.relations[n.id]={gifts:0};return ok(n.name+'：'+n.dialogue);}
      if(p[1]==='quest'&&p.length===4){const q=worldQuestInfo(s).find(q=>q.id===p[3]);if(!q)return bad('没有此支线。');if(p[2]==='accept'){if(!q.canAccept)return bad(q.reason);w.quests[q.id]={baseline:q.kind==='delivery'?0:measure(s,q),acceptedAt:s.time,claimedAt:null,observed:null};return ok('接取 '+q.name+'。'+q.description);}if(p[2]==='claim'){if(!q.canClaim)return bad(q.reason);const r=w.quests[q.id];r.observed=q.kind==='delivery'?q.target:measure(s,q);h.pay(s,q.cost||{});h.grant(s,q.reward);r.claimedAt=s.time;return ok(q.name+'完成，一次奖励已收入行囊。');}}
      if(p[1]==='talent'&&p[2]==='learn'&&p.length===4){const t=talentInfo(s).entries.find(t=>t.id===p[3]);if(!t?.available)return bad(t?.reason||'没有此天赋。');const old=h.stats(s);w.talents.push(t.id);const now=h.stats(s);s.player.hp=Math.min(now.maxHp,s.player.hp/old.maxHp*now.maxHp);s.player.mp=Math.min(now.maxMp,s.player.mp/old.maxMp*now.maxMp);return ok('领悟 '+t.name+'。'+t.description);}
      if(p[1]==='romance'&&p.length===4){const n=C.WORLD_NPCS[p[3]],r=n&&romanceInfo(s,n);if(!r)return bad('这位人物没有道侣互动。');if(p[2]==='gift'){if(!r.canGift)return bad(r.giftReason);h.pay(s,r.giftCost);w.relations[n.id].gifts++;return ok(n.name+'接受了礼物，好感增加一点。');}if(p[2]==='bond'){if(!r.canBond)return bad(r.bondReason);h.pay(s,r.bondCost);w.partner=n.id;return ok(n.name+'与你互许承诺，结为道侣。可以邀请她一同历练。');}if(p[2]==='travel'){if(!r.canTravel)return bad(r.travelReason);w.companion=w.companion===n.id?null:n.id;return ok(w.companion?n.name+'与你同行。':n.name+'留在驿站等候。');}}
      if(p[1]==='thief'&&p.length===3){const info=thiefInfo(s,C.WORLD_NPCS.emptyHand),c=info.choices.find(c=>c.id===p[2]);if(!c?.available)return bad(c?.reason||'无法作出此处置。');h.pay(s,c.cost);h.grant(s,c.reward);w.thief=c.id;return ok(c.description);}
      if(p[1]==='trait'&&p[2]==='train'&&p.length===5){const d=discipleTraitInfo(s).find(d=>d.id===p[3]),t=d?.trainOptions.find(t=>t.id===p[4]);if(!t?.available)return bad(t?.reason||'无法训导。');const old=h.stats(s);h.pay(s,t.cost);w.discipleTraits[d.id]=t.id;const now=h.stats(s);s.player.hp=Math.min(now.maxHp,s.player.hp/old.maxHp*now.maxHp);s.player.mp=Math.min(now.maxMp,s.player.mp/old.maxMp*now.maxMp);return ok(d.name+'的训导完成：'+t.name+'。');}return bad('未知山海互动。');
    }
    function onKill(s,e){if(!own(C.EXPANSION_ENEMIES,e.type))return;s.worldlife.kills[e.type]=(s.worldlife.kills[e.type]||0)+1;const key=s.mapId+':'+e.id,n=s.worldlife.stolen[key]||0;if(n){s.drops.push({x:e.x,y:e.y,type:'stones',amount:n});delete s.worldlife.stolen[key];}}
    function onVisit(s,id){s.worldlife.visits[id]=(s.worldlife.visits[id]||0)+1;}
    function steal(s,e){const key=s.mapId+':'+e.id,current=s.worldlife.stolen[key]||0,n=Math.min(12,s.player.stones,120-current);if(!n)return;s.player.stones-=n;s.worldlife.stolen[key]=current+n;h.log(s,'飞贼夺走'+n+'灵石，斩倒它可夺回。');}
    function poison(s,damage){s.worldlife.poison.life=4;s.worldlife.poison.damage=Math.max(s.worldlife.poison.damage,damage);}
    function revive(s){s.worldlife.poison={life:0,damage:0,tick:0};}
    function step(s,dt){const w=s.worldlife;if(s.dead)return;const poison=w.poison;if(poison.life>0){poison.life=Math.max(0,poison.life-dt);poison.tick+=dt;if(poison.tick>=.7){poison.tick-=.7;h.hurtPlayer(s,poison.damage,s.player.x,s.player.y);}if(poison.life===0){poison.damage=0;poison.tick=0;}}if(s.dead)return;w.companionCd=Math.max(0,w.companionCd-dt);if(!w.companion||w.companionCd>0||h.isSafe(s))return;const n=C.WORLD_NPCS[w.companion],st=h.stats(s),field=n.companionEffect==='heal'?'hp':'mp',max=n.companionEffect==='heal'?st.maxHp:st.maxMp;if(s.player[field]>=max)return;s.player[field]=Math.min(max,s.player[field]+max*(field==='hp'?.05:.08));w.companionCd=effects(s).companionCooldown;h.effect(s,field==='hp'?'heal':'ring',s.player.x,s.player.y,.7,55,{color:n.color,companionId:n.id});}
    function validate(raw,s,version){if(version<7){init(s);return;}const fail=()=>{throw Error('Invalid worldlife save');},obj=(o,keys)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>['__proto__','constructor','prototype'].includes(k)||keys&&!keys.includes(k)))fail();return o;},num=(x,a,b,int=false)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<a||x>b||int&&!Number.isInteger(x))fail();return x;},ids=(a,allowed,max)=>{if(!Array.isArray(a)||a.length>max||new Set(a).size!==a.length||a.some(id=>!allowed.includes(id)))fail();return a.slice();};
      const a=obj(raw.worldlife,['schema','met','quests','kills','visits','talents','relations','partner','companion','companionCd','thief','discipleTraits','stolen','poison']);if(a.schema!==1)fail();init(s);const w=s.worldlife;w.met=ids(a.met,Object.keys(C.WORLD_NPCS),12);if(w.met.some(id=>!s.progress.visited.includes(C.WORLD_NPCS[id].mapId)))fail();for(const[id,n]of Object.entries(obj(a.kills,Object.keys(C.EXPANSION_ENEMIES))))w.kills[id]=num(n,0,s.quests.kills,true);for(const[id,n]of Object.entries(obj(a.visits,Object.keys(C.MAPS)))){w.visits[id]=num(n,1,1e7,true);if(!s.progress.visited.includes(id))fail();}for(const[id,r]of Object.entries(obj(a.quests,Object.keys(C.WORLD_QUESTS)))){const q=C.WORLD_QUESTS[id];obj(r,['baseline','acceptedAt','claimedAt','observed']);if(!w.met.includes(q.npcId))fail();const baseline=num(r.baseline,0,q.kind==='delivery'?0:measure(s,q),true),acceptedAt=num(r.acceptedAt,0,s.time);let claimedAt=null,observed=null;if(r.claimedAt!==null){claimedAt=num(r.claimedAt,acceptedAt,s.time);observed=num(r.observed,q.kind==='delivery'?q.target:baseline+q.target,q.kind==='delivery'?q.target:measure(s,q),true);}else if(r.observed!==null)fail();w.quests[id]={baseline,acceptedAt,claimedAt,observed};}for(const[id,r]of Object.entries(w.quests))for(const key of C.WORLD_QUESTS[id].prerequisites){const prior=w.quests[key];if(prior?.claimedAt==null||r.acceptedAt<prior.claimedAt)fail();}
      w.talents=ids(a.talents,Object.keys(C.TALENTS),18);for(const id of w.talents){const t=C.TALENTS[id];if(s.player.realm<t.realmRequired||t.prerequisites.some(p=>!w.talents.includes(p)))fail();}if(talentInfo(s).pointsAvailable<0)fail();for(const[id,r]of Object.entries(obj(a.relations,['yueLing','yunSheng']))){obj(r,['gifts']);if(!w.met.includes(id))fail();w.relations[id]={gifts:num(r.gifts,0,3,true)};}for(const id of w.met.filter(id=>C.WORLD_NPCS[id].romance))if(!w.relations[id])fail();if(a.partner!==null){const n=C.WORLD_NPCS[a.partner];if(!n?.romance||!w.met.includes(n.id)||Object.values(C.WORLD_QUESTS).filter(q=>q.npcId===n.id).some(q=>w.quests[q.id]?.claimedAt==null))fail();w.partner=n.id;if(romanceInfo(s,n).affinity<6)fail();}if(a.companion!==null&&a.companion!==w.partner)fail();w.companion=a.companion;w.companionCd=num(a.companionCd,0,12);if(a.thief!==null){if(!['mercy','justice'].includes(a.thief)||['thiefDebts','thiefRepay'].some(id=>w.quests[id]?.claimedAt==null))fail();w.thief=a.thief;}for(const[id,t]of Object.entries(obj(a.discipleTraits,Object.keys(C.SECT_DISCIPLES)))){if(!own(C.DISCIPLE_TRAITS,t)||!s.sect.disciples[id].recruited||!s.management.enabled||t==='loyal'&&w.thief!=='mercy'||t==='careful'&&w.thief!=='justice')fail();w.discipleTraits[id]=t;}for(const[key,n]of Object.entries(obj(a.stolen))){const[map,id]=key.split(':');if(!s.progress.visited.includes(map)||!s.worlds[map]?.enemies.some(e=>e.id===id&&e.type==='streetBandit'&&e.hp>0))fail();w.stolen[key]=num(n,1,120,true);}
      if(Object.values(w.kills).reduce((sum,n)=>sum+n,0)>s.quests.kills)fail();const p=obj(a.poison,['life','damage','tick']);w.poison={life:num(p.life,0,4),damage:num(p.damage,0,20),tick:num(p.tick,0,.7)};if(w.poison.life===0&&(w.poison.damage!==0||w.poison.tick!==0)||w.poison.life>0&&w.poison.damage<=0)fail();
    }
    function worldlifeInfo(s){return{npcs:Object.keys(C.WORLD_NPCS).map(id=>worldNpcInfo(s,id)),quests:worldQuestInfo(s),talents:talentInfo(s),disciples:discipleTraitInfo(s),partner:s.worldlife.partner,companion:s.worldlife.companion};}
    return{init,action,step,validate,worldNpcInfo,worldQuestInfo,talentInfo,discipleTraitInfo,worldlifeInfo,effects,bonuses,productionBonus,fatigueBonus,onKill,onVisit,steal,poison,revive};
  };
});
