'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {X,C,fresh,ledger,checked,failed,advance,roundtrip,naturalBot}=require('./depth-helpers.cjs');
const eq=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} versus ${b}`);

// Controlled damage boundaries use real spawned route enemies and real attacks.
// Position, enemy status and missing MP are explicitly arranged only for isolated
// paired trigger measurements. The separate natural-loop test never does this.
function combat({mindset=null,weapon='starterSword',primary='sword',secondary='flame',final='stabilize'}={}){
 const s=fresh();if(s.equipment.weapon!==weapon)checked(s,'equip:'+weapon);checked(s,'technique:'+primary);checked(s,'secondary:'+secondary);if(mindset)checked(s,'journey:build:equip:0:'+mindset);checked(s,'journey:route:start:frostVault');
 for(const choice of ['warm','open',final]){const station=X.expeditionInfo(s).station;s.player.x=station.x;s.player.y=station.y;X.step(s,{},.05);checked(s,'journey:route:choose:'+choice);if(choice===final)break;for(const target of [...s.enemies]){s.player.x=target.x-65;s.player.y=target.y;for(let i=0;target.hp>0;i++){assert.ok(i<1500);if(s.player.hp<X.stats(s).maxHp*.55)checked(s,'heal');const d=Math.hypot(target.x-s.player.x,target.y-s.player.y)||1;X.step(s,{mx:d>60?(target.x-s.player.x)/d:0,my:d>60?(target.y-s.player.y)/d:0,attack:true,aimX:target.x,aimY:target.y},.05);assert.equal(s.dead,false);}}}
 advance(s,1.5);const e=s.enemies[0];s.player.x=e.x-65;s.player.y=e.y;s.player.mp=100;return{s,e};
}
function damage(s,e,input){const hp=e.hp;X.step(s,{aimX:e.x,aimY:e.y,...input},.05);for(let i=0;hp===e.hp&&i<30;i++)X.step(s,{},.05);assert.ok(e.hp<hp,'Real emitted attack must hit');return hp-e.hp;}
test('burn and frost mindsets increase real paired hit damage, consume status and cannot retrigger during cooldown',()=>{
 for(const [id,status,ratio]of[['burnHarvest','burn',1.45],['frostShatter','slow',1.35]]){const a=combat(),b=combat({mindset:id});for(const q of[a,b]){q.e[status]=2;if(status==='burn')q.e.burnDamage=0;}const before=b.s.player.mp,plain=damage(a.s,a.e,{attack:true}),boosted=damage(b.s,b.e,{attack:true});eq(boosted/plain,ratio);assert.equal(b.s.journey.build.triggers[id],1);assert.equal(b.e[status],0);assert.ok(b.s.journey.build.cooldowns[id]>0);if(id==='burnHarvest')eq(b.s.player.mp-a.s.player.mp,8);roundtrip(b.s);}
 const s=fresh();checked(s,'journey:build:equip:0:burnHarvest');failed(s,'journey:build:equip:1:rootFlame');failed(s,'journey:build:equip:1:burnHarvest');checked(s,'journey:build:equip:0:none');checked(s,'journey:build:equip:0:rootFlame');roundtrip(s);
});
test('root-flame transforms actual rooted fire impact into stronger damage and continuing burn',()=>{
 const a=combat({weapon:'spiritStaff',primary:'flame',secondary:'wood'}),b=combat({mindset:'rootFlame',weapon:'spiritStaff',primary:'flame',secondary:'wood'});for(const q of[a,b]){q.e.rooted=3;q.s.player.x=q.e.x-350;}const plain=damage(a.s,a.e,{skill:true}),boosted=damage(b.s,b.e,{skill:true});eq(boosted/plain,1.6);assert.equal(b.e.rooted,0);assert.ok(b.e.burn>0&&b.e.burnDamage>0);assert.equal(b.s.journey.build.triggers.rootFlame,1);roundtrip(b.s);
});
test('real shield absorption arms one sword retaliation and consumes the prepared echo',()=>{
 const a=combat(),b=combat({mindset:'shieldEcho'});for(const q of[a,b]){q.s.player.shield=80;q.s.player.shieldTime=10;q.s.player.invuln=0;q.s.projectiles.push({x:q.s.player.x,y:q.s.player.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:q.e.id,damage:100});X.step(q.s,{},.05);assert.ok(q.s.player.shield<80);}assert.ok(b.s.journey.build.armed.echoUntil>b.s.time);const plain=damage(a.s,a.e,{attack:true}),boosted=damage(b.s,b.e,{attack:true});eq(boosted/plain,1.6);assert.equal(b.s.journey.build.armed.echoUntil,0);assert.equal(b.s.journey.build.triggers.shieldEcho,1);roundtrip(b.s);
});
test('dash prepares an actual arrow with extra damage and finite two-target penetration',()=>{
 const a=combat({weapon:'ironBow'}),b=combat({mindset:'windStep',weapon:'ironBow',final:'take'});const second=b.s.enemies[1];second.x=b.e.x+150;second.y=b.e.y;second.rooted=2;const secondHp=second.hp;for(const q of[a,b]){q.s.player.x=q.e.x-260;q.s.player.y=q.e.y;X.step(q.s,{dash:true,mx:-1,aimX:q.e.x,aimY:q.e.y},.05);advance(q.s,.2);}const plain=damage(a.s,a.e,{attack:true}),boosted=damage(b.s,b.e,{attack:true});eq(boosted/plain,1.35);assert.equal(b.s.journey.build.triggers.windStep,1);assert.equal(b.s.journey.build.armed.windUntil,0);const bolt=b.s.projectiles.find(p=>p.windPrepared);assert.ok(bolt&&bolt.pierce<=2&&bolt.hits.includes(b.e.id));for(let i=0;i<30&&second.hp===secondHp;i++)X.step(b.s,{},.05);assert.ok(second.hp<secondHp,'The same prepared arrow must actually hit the second target');assert.ok(bolt.hits.includes(second.id));assert.equal(bolt.hits.length,2);roundtrip(b.s);
});
test('cycle-breath returns eight extra MP only after a real generating pair impacts the enemy',()=>{
 const a=combat({weapon:'spiritStaff',primary:'wood',secondary:'flame'}),b=combat({mindset:'cycleBreath',weapon:'spiritStaff',primary:'wood',secondary:'flame'});for(const q of[a,b])damage(q.s,q.e,{skill:true});const plain=damage(a.s,a.e,{secondary:true}),boosted=damage(b.s,b.e,{secondary:true});eq(boosted,plain);eq(b.s.player.mp-a.s.player.mp,8);assert.equal(b.s.journey.build.triggers.cycleBreath,1);roundtrip(b.s);
});
test('two real retreat strategies trade time and materials for actual next-realm preparation, and battle focus affects recovery',t=>{
 const raw=fs.readFileSync(path.join(__dirname,'v2-save.fixture.json'),'utf8'),calm=X.deserialize(raw),rushed=X.deserialize(raw);const base=X.cultivationInfo(calm).xpNeeded;checked(calm,'journey:retreat:start:steady');checked(rushed,'journey:retreat:start:driven');assert.deepEqual(calm.journey.retreat.paidCost,{stones:20,herbs:2});assert.deepEqual(rushed.journey.retreat.paidCost,{stones:30,core:1});checked(calm,'journey:retreat:steer:condense');failed(calm,'journey:retreat:steer:condense');roundtrip(calm);advance(calm,12);checked(calm,'journey:retreat:steer:breathe');advance(calm,12);advance(rushed,20);assert.equal(X.retreatInfo(calm).quality,'澄明');assert.equal(X.retreatInfo(rushed).quality,'散乱');roundtrip(calm);roundtrip(rushed);checked(calm,'journey:retreat:claim:foundation');checked(rushed,'journey:retreat:claim:foundation');assert.equal(X.cultivationInfo(calm).xpNeeded,Math.ceil(base*.85));assert.equal(X.cultivationInfo(rushed).xpNeeded,Math.ceil(base*.95));failed(calm,'journey:retreat:claim:foundation');roundtrip(calm);roundtrip(rushed);
 const focused=fresh(),plain=fresh();checked(focused,'journey:retreat:start:steady');advance(focused,24);checked(focused,'journey:retreat:claim:battle');focused.player.mp=plain.player.mp=100;advance(focused,1);advance(plain,1);eq(focused.player.mp-plain.player.mp,1.2);assert.equal(X.stats(focused).manaRegen-X.stats(plain).manaRegen,1.2);roundtrip(focused);const paused=ledger(focused);X.step(focused,{},0);assert.deepEqual(ledger(focused),paused);focused.dead=true;X.step(focused,{},.05);assert.deepEqual(ledger(focused),paused);focused.dead=false;advance(focused,90);assert.equal(focused.journey.cultivation.battleFocus,0);roundtrip(focused);t.diagnostic(JSON.stringify({stableRequirement:X.cultivationInfo(calm).xpNeeded,rushedRequirement:X.cultivationInfo(rushed).xpNeeded,originalRequirement:base}));
});
test('route choices change actual enemy counts and paid supplies, preserve worlds and deny travel/old activity overlap',()=>{
 const a=fresh(),b=fresh(),world=JSON.parse(X.serialize(a)).worlds;for(const s of[a,b]){checked(s,'journey:route:start:emberConvoy');failed(s,'sect:mission:bounty');failed(s,'travel:sect');failed(s,'journey:retreat:start:steady');const p=X.expeditionInfo(s).station;s.player.x=p.x;s.player.y=p.y;X.step(s,{},.05);roundtrip(s);}const before=ledger(a);checked(a,'journey:route:choose:cool');checked(b,'journey:route:choose:rush');assert.equal(a.player.frost,before.wallet.frost-2);assert.equal(a.enemies.length,2);assert.equal(b.enemies.length,3);assert.equal(C.ROUTES.emberConvoy.stations[0].options.find(o=>o.id==='rush').hazard,'fire');roundtrip(a);roundtrip(b);failed(a,'journey:route:choose:rush');checked(a,'journey:route:leave');assert.equal(a.mapId,'sect');assert.deepEqual(JSON.parse(X.serialize(a)).worlds.red,world.red);assert.equal(a.journey.routes.completed.emberConvoy,undefined);assert.equal(a.player.stones,before.wallet.stones);failed(a,'journey:route:leave');roundtrip(a);
});
test('six-slot, route, retreat and relationship forgery cannot manufacture preparations or support',()=>{
 const s=fresh(),raw=X.serialize(s);for(const change of[d=>d.journey.build.slots=['burnHarvest','rootFlame'],d=>d.journey.build.slots=['windStep','windStep'],d=>d.journey.cultivation.preparations={'8':.15},d=>d.journey.cultivation.battleFocus=90,d=>d.journey.supports.herbal=120,d=>d.journey.routes.history=[{id:'herbTrail',choices:['guard','identify','escort'],realm:7,time:d.time}],d=>d.journey.relations.elder={done:[{index:0,baseline:0,observed:5,acceptedAt:d.time,time:d.time}],active:null,nextAt:d.time,lastSupportAt:null}]){const bad=JSON.parse(raw);change(bad);assert.throws(()=>X.deserialize(JSON.stringify(bad)));}
});
