'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {X,fresh,ledger,checked,failed,advance,step,roundtrip}=require('./depth-helpers.cjs');
const facility=(s,id)=>X.managementInfo(s).facilities.find(f=>f.id===id);
function enable(s){for(const [id,f]of Object.entries(s.sect.facilities))if(f.stored)checked(s,'sect:claim:'+id);checked(s,'management:enable');return s;}
function clean(s){enable(s);for(const id of Object.keys(s.management.facilities))checked(s,'management:cancel:'+id);return s;}
function finish(s,id){for(let i=0;facility(s,id).stored===0;i++){assert.ok(i<4000,'Production must finish with real available inputs');step(s);}return facility(s,id);}

test('management transfers genuine old progress, charges at batch start and preserves committed work when cancelling',()=>{
 const s=fresh();failed(s,'management:enable');const old=X.sectInfo(s).facilities.map(f=>({id:f.id,progress:f.progress,duration:f.duration}));checked(s,'sect:claim:garden');const before=ledger(s);checked(s,'management:enable');assert.deepEqual(ledger(s).wallet,before.wallet);
 for(const f of old)assert.ok(Math.abs(s.management.facilities[f.id].carry-f.progress/f.duration)<1e-8);const start=ledger(s);step(s);
 for(const f of old){const b=s.management.facilities[f.id].batch;assert.ok(b);assert.ok(Math.abs(b.progress-(f.progress/f.duration*b.duration+.05))<1e-6);}
 assert.equal(s.player.herbs,start.wallet.herbs-3);assert.equal(s.player.stones,start.wallet.stones-9);roundtrip(s);const batch=structuredClone(s.management.facilities.garden.batch);checked(s,'management:order:garden:timber:3');checked(s,'management:cancel:garden');assert.deepEqual(s.management.facilities.garden.batch,batch);failed(s,'management:position:garden:center');failed(s,'management:policy:qinghe:urgent');finish(s,'garden');const ready=ledger(s);checked(s,'management:claim:garden');assert.equal(s.player.herbs,ready.wallet.herbs+4);failed(s,'management:claim:garden');roundtrip(s);
});

test('matching position and actual upstream production produce shorter paid batches, with unchanged recipe output',t=>{
 const aligned=clean(fresh()),isolated=clean(fresh());for(const s of [aligned,isolated])checked(s,'management:order:forge:ember:1');checked(aligned,'management:order:garden:timber:1');
 const a=facility(aligned,'forge').recipes.find(r=>r.id==='ember'),b=facility(isolated,'forge').recipes.find(r=>r.id==='ember');assert.ok(a.duration<b.duration);assert.ok(Math.abs(a.duration-b.duration/1.12)<1e-12);assert.ok(facility(aligned,'forge').sources.some(x=>x.includes('上游相生')));step(aligned);step(isolated);assert.ok(aligned.management.facilities.forge.batch.duration<isolated.management.facilities.forge.batch.duration);assert.deepEqual(aligned.management.facilities.forge.batch.reward,isolated.management.facilities.forge.batch.reward);roundtrip(aligned);roundtrip(isolated);
 const wood=clean(fresh()),misplaced=clean(fresh());checked(misplaced,'management:position:garden:center');for(const s of [wood,misplaced])checked(s,'management:order:garden:timber:1');step(wood);step(misplaced);assert.ok(wood.management.facilities.garden.batch.duration<misplaced.management.facilities.garden.batch.duration);assert.ok(Math.abs(wood.management.facilities.garden.batch.duration*1.2-misplaced.management.facilities.garden.batch.duration)<1e-6);failed(wood,'management:position:forge:east');t.diagnostic(JSON.stringify({upstreamSeconds:a.duration,isolatedSeconds:b.duration,matchedSeconds:wood.management.facilities.garden.batch.duration,mismatchedSeconds:misplaced.management.facilities.garden.batch.duration}));
});

test('three-batch storage blocks payment, claimed quantity is exact and pause/death preserve all production',()=>{
 const s=clean(fresh());checked(s,'management:order:garden:timber:6');advance(s,90);assert.equal(s.management.facilities.garden.stored.length,3);assert.equal(s.management.facilities.garden.order.quantity,3);assert.equal(s.management.facilities.garden.batch,null);const full=ledger(s);advance(s,20);assert.deepEqual(ledger(s).wallet,full.wallet);assert.deepEqual(s.management.facilities.garden,full.management.facilities.garden);roundtrip(s);
 const paused=ledger(s);for(let i=0;i<100;i++)X.step(s,{},0);assert.deepEqual(ledger(s),paused);s.dead=true;for(let i=0;i<100;i++)X.step(s,{},.05);assert.deepEqual(ledger(s),paused);s.dead=false;checked(s,'management:claim:garden');assert.equal(s.player.spiritwood,full.wallet.spiritwood+6);failed(s,'management:claim:garden');step(s);assert.ok(s.management.facilities.garden.batch);assert.equal(s.player.herbs,full.wallet.herbs-1);roundtrip(s);
});

test('urgent production has a real material cost and fatigue causes automatic recovery, while manual rest preserves progress',t=>{
 const balanced=clean(fresh()),urgent=clean(fresh()),careful=clean(fresh());checked(urgent,'management:policy:qinghe:urgent');checked(careful,'management:policy:qinghe:careful');for(const s of [balanced,urgent,careful])checked(s,'management:order:garden:timber:1');step(balanced);step(urgent);step(careful);const bs=balanced.management.facilities.garden.batch,us=urgent.management.facilities.garden.batch,cs=careful.management.facilities.garden.batch;assert.equal(us.cost.herbs,bs.cost.herbs+1);assert.ok(us.duration<bs.duration&&bs.duration<cs.duration);advance(balanced,5);advance(urgent,5);advance(careful,5);assert.ok(urgent.management.workers.qinghe.fatigue>balanced.management.workers.qinghe.fatigue);assert.ok(careful.management.workers.qinghe.fatigue<balanced.management.workers.qinghe.fatigue);
 checked(urgent,'management:rest:qinghe');const progress=urgent.management.facilities.garden.batch.progress,oldFatigue=urgent.management.workers.qinghe.fatigue;advance(urgent,4);assert.equal(urgent.management.facilities.garden.batch.progress,progress);assert.ok(urgent.management.workers.qinghe.fatigue<oldFatigue);assert.equal(urgent.management.workers.qinghe.resting,true);roundtrip(urgent);advance(urgent,5);assert.equal(urgent.management.workers.qinghe.resting,false);
 let resting=false,completed=0;for(let i=0;i<5000;i++){const v=balanced.management.facilities.garden;if(v.stored.length){completed+=v.stored.length;checked(balanced,'management:claim:garden');}if(!v.order)checked(balanced,'management:order:garden:timber:6');step(balanced);if(balanced.management.workers.qinghe.resting){resting=true;break;}}assert.ok(resting&&completed>=6,'Actual continued paid work must reach fatigue rest');const tired=balanced.management.workers.qinghe.fatigue;advance(balanced,8);assert.ok(balanced.management.workers.qinghe.fatigue<tired);roundtrip(balanced);t.diagnostic(JSON.stringify({balanced:bs.duration,urgent:us.duration,careful:cs.duration,completedBeforeRest:completed,fatigueAtRest:tired}));
});

test('initially absent spiritwood is earned by production and research consumes it, improves processes and stops at three',()=>{
 const s=fresh();assert.equal(s.player.spiritwood,0);clean(s);assert.equal(s.player.spiritwood,1,'One actual old garden batch includes one earned spiritwood');checked(s,'management:order:garden:timber:3');advance(s,90);checked(s,'management:claim:garden');assert.equal(s.player.spiritwood,7);checked(s,'management:order:library:research:3');const before=ledger(s);step(s);assert.equal(s.player.spiritwood,before.wallet.spiritwood-1);assert.equal(s.player.essence,before.wallet.essence-1);assert.equal(s.sect.contribution,before.sect.contribution-2);roundtrip(s);failed(s,'management:order:library:research:3');advance(s,160);assert.equal(s.management.facilities.library.stored.length,3);failed(s,'management:order:library:research:1');checked(s,'management:claim:library');assert.equal(s.workshop.research,3);failed(s,'management:order:library:research:1');failed(s,'management:claim:library');roundtrip(s);
});

test('malformed process and management actions fail without resource or progression changes',()=>{
 const s=clean(fresh());for(const id of ['management:order:garden:timber:0','management:order:garden:timber:7','management:order:garden:iron:1','management:order:garden:__proto__:1','management:policy:qinghe:constructor','management:rest:__proto__','management:claim:constructor','management:position:toString:east','workshop:brew:start:constructor:essence','workshop:brew:start:healing:__proto__','workshop:forge:start:ironBow:toString','workshop:forge:temper:constructor'])failed(s,id);roundtrip(s);
});
