'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {X,C,fresh,ledger,checked,failed,roundtrip,naturalBot}=require('./depth-helpers.cjs');
const out=process.env.SHANHAI_V6_OUTPUT?path.resolve(process.env.SHANHAI_V6_OUTPUT):null;
function route(s,bot,id,choices,proof){bot.action('journey:route:start:'+id);roundtrip(s);for(const choice of choices){bot.walk(X.expeditionInfo(s).station);assert.equal(s.journey.active.phase,'choice');roundtrip(s);bot.action('journey:route:choose:'+choice);const entry={stage:s.journey.active.stage,choice,enemies:s.enemies.map(e=>e.type),paid:structuredClone(s.journey.active.paidCost),objective:structuredClone(s.journey.active.objective)};roundtrip(s);for(const e of [...s.enemies])if(e.hp>0)bot.fight(e);entry.outcome=s.journey.active.phase;entry.remainingHp=s.player.hp;roundtrip(s);proof.push(entry);}assert.equal(s.journey.active.phase,'complete');const wallet=ledger(s).wallet,completed=s.journey.routes.completed[id];bot.wait(2.1);assert.equal(s.journey.active,null);assert.equal(s.journey.routes.completed[id],completed);assert.equal(s.player.stones,wallet.stones);roundtrip(s);}
function collect(s,bot,kind,count){const nodeType=kind==='herbs'?'herb':kind;const initial=s.progress.gathered[kind]||0;for(let attempts=0;(s.progress.gathered[kind]||0)-initial<count;attempts++){assert.ok(attempts<80,'Gather actual available '+kind);const nodes=s.nodes.filter(n=>n.type===nodeType&&n.ready<=0);if(!nodes.length){const next=s.nodes.filter(n=>n.type===nodeType).sort((a,b)=>a.ready-b.ready)[0];assert.ok(next);bot.wait(next.ready+.1);continue;}nodes.sort((a,b)=>Math.hypot(a.x-s.player.x,a.y-s.player.y)-Math.hypot(b.x-s.player.x,b.y-s.player.y));bot.walk(nodes[0]);bot.frame({interact:true});}roundtrip(s);}
function accept(s,bot,id){bot.station(id);const info=X.relationshipInfo(s,id);assert.equal(info.contract.progress,info.contract.kind==='delivery'?Math.min(info.contract.target,s.player[info.contract.item]):0);bot.action('journey:npc:'+id+':accept');roundtrip(s);failed(s,'journey:npc:'+id+':accept');}
function deliver(s,bot,id){bot.station(id);assert.equal(X.relationshipInfo(s,id).contract.ready,true);bot.action('journey:npc:'+id+':deliver');roundtrip(s);failed(s,'journey:npc:'+id+':deliver');}

test('normal earned V5 resources form a complete production, refinement, inscription, route, six-round relationship and cultivation loop',t=>{
 const s=fresh(),bot=naturalBot(s),proof=[],start=ledger(s),originalNpc=structuredClone(s.npcProgress);assert.equal(s.player.spiritwood,0);for(const[id,f]of Object.entries(s.sect.facilities))if(f.stored)bot.action('sect:claim:'+id);bot.action('management:enable');for(const id of Object.keys(s.management.facilities))bot.action('management:cancel:'+id);bot.action('management:order:garden:timber:6');while(s.player.spiritwood<13){if(s.management.facilities.garden.stored.length)bot.action('management:claim:garden');bot.wait(.2);}assert.equal(s.player.spiritwood,13);roundtrip(s);proof.push({step:'real-production',fromWood:start.wallet.spiritwood,toWood:s.player.spiritwood,costs:bot.trace.filter(a=>a.id.startsWith('management:'))});
 bot.station('alchemy');bot.action('workshop:brew:start:healing:wood');let cleaned=0;while(X.brewingInfo(s).phase==='extract'){const a=X.brewingInfo(s),fire=a.temperature<a.targetTemperature-1?3:0;if(a.fire!==fire)bot.action('workshop:brew:fire:'+fire);if(a.canPurify&&cleaned<2){bot.action('workshop:brew:purify');cleaned++;}bot.frame();}bot.action('workshop:brew:seal:slow');bot.wait(6);const medicine=structuredClone(X.brewingInfo(s).output);bot.action('workshop:brew:claim');proof.push({step:'refined-medicine',medicine});roundtrip(s);
 bot.station('forge');bot.action('workshop:forge:start:ironBow:guard');while(X.forgingInfo(s).phase==='heat'){const a=X.forgingInfo(s),fire=a.temperature<a.targetTemperature-1?3:0;if(a.fire!==fire)bot.action('workshop:forge:fire:'+fire);if(a.canHammer&&Math.abs(a.temperature-a.targetTemperature)<10)bot.action('workshop:forge:hammer');bot.frame();}bot.action('workshop:forge:temper:wood');bot.wait(6);bot.action('workshop:forge:claim');proof.push({step:'real-inscription',mod:structuredClone(s.workshop.mods.ironBow),stats:X.stats(s)});roundtrip(s);
 bot.action('journey:build:equip:0:windStep');bot.action('journey:build:equip:1:burnHarvest');bot.action('technique:flame_immortal');bot.action('secondary:wood');
 // Two actors advance together, with actual accepted-after kills, paid deliveries
 // and twenty seconds between contracts. No old kill count or rapport carries over.
 for(let round=0;round<6;round++){if(round)bot.wait(20.1);for(const id of['elder','disciple'])accept(s,bot,id);const contracts=['elder','disciple'].map(id=>X.relationshipInfo(s,id).contract);if(contracts.some(c=>c.kind==='kills'))route(s,bot,'herbTrail',['harvest','raid','escort'],proof);for(const id of['elder','disciple'])deliver(s,bot,id);}
 for(const id of['elder','disciple'])assert.equal(s.journey.relations[id].done.length,6);const preSupport=X.serialize(s);bot.station('elder');const cost=X.relationshipInfo(s,'elder').supports[0].cost,before=ledger(s);bot.action('journey:npc:elder:support:study');for(const[k,n]of Object.entries(cost))assert.equal(s.player[k],before.wallet[k]-n);bot.station('disciple');bot.action('journey:npc:disciple:support:escort');roundtrip(s);proof.push({step:'persistent-sect-relations',completed:{elder:6,disciple:6},supports:structuredClone(s.journey.supports)});
 bot.travel('main');for(let round=0;round<6;round++){if(round)bot.wait(20.1);accept(s,bot,'herbalist');const c=X.relationshipInfo(s,'herbalist').contract;if(c.kind!=='delivery')collect(s,bot,c.kind,c.target);deliver(s,bot,'herbalist');}bot.station('herbalist');bot.action('journey:npc:herbalist:support:herbal');assert.equal(s.journey.relations.herbalist.done.length,6);assert.equal(X.relationshipBonus(s,'qinghe'),1.15);roundtrip(s);
 bot.travel('red');for(let round=0;round<6;round++){if(round)bot.wait(20.1);accept(s,bot,'fireArtisan');const c=X.relationshipInfo(s,'fireArtisan').contract;if(c.kind==='kills')route(s,bot,'emberConvoy',['rush','cart','break'],proof);else if(c.kind!=='delivery')collect(s,bot,c.kind,c.target);deliver(s,bot,'fireArtisan');}bot.station('fireArtisan');bot.action('journey:npc:fireArtisan:support:artisan');assert.equal(s.journey.relations.fireArtisan.done.length,6);assert.equal(X.relationshipBonus(s,'yanming'),1.2);roundtrip(s);
 bot.travel('sect');bot.action('journey:retreat:start:steady');bot.action('journey:retreat:steer:condense');bot.wait(12);bot.action('journey:retreat:steer:breathe');bot.wait(12);bot.action('journey:retreat:claim:battle');assert.equal(s.journey.cultivation.battleFocus,90);roundtrip(s);assert.ok(s.journey.build.triggers.burnHarvest>0);assert.ok(s.player.hp>0);assert.equal(s.dead,false);assert.deepEqual(s.npcProgress,originalNpc,'New contracts do not rewrite original interactions');
 const supportSave=X.serialize(s);bot.wait(121);roundtrip(s);assert.ok(Object.values(s.journey.supports).every(v=>v===0),'Expired help remains valid and cannot be refreshed for free');const final=X.serialize(s);proof.push({step:'persistent-world',completedRelations:Object.fromEntries(Object.entries(s.journey.relations).map(([id,r])=>[id,r.done.length])),routes:s.journey.routes,remaining:ledger(s).wallet,medicine,mods:s.workshop.mods,stats:X.stats(s),triggers:s.journey.build.triggers,metrics:bot.metrics()});
 if(out){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'new-natural-save.json'),final);fs.writeFileSync(path.join(out,'natural-support-save.json'),supportSave);fs.writeFileSync(path.join(out,'natural-pre-support-save.json'),preSupport);fs.writeFileSync(path.join(out,'natural-loop-report.json'),JSON.stringify({boundary:'Unchanged public naturally earned V5 save; only paid gameplay actions, movement, gather and combat inputs. No position, HP, MP, materials, enemies, stage or rewards are assigned.',proof,trace:bot.trace,initial:start.wallet,final:ledger(s).wallet},null,2));}t.diagnostic(JSON.stringify({boundary:'Normal action and input only',completedRelations:Object.fromEntries(Object.entries(s.journey.relations).map(([id,r])=>[id,r.done.length])),routes:s.journey.routes.completed,metrics:bot.metrics()}));
});
