'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {X,ledger,checked,failed,advance,roundtrip,atStation,naturalBot}=require('./depth-helpers.cjs');
const BYTES=fs.readFileSync(path.join(__dirname,'v6-depth.fixture.json'));assert.equal(crypto.createHash('sha256').update(BYTES).digest('hex'),'51ba4153e63d8babb98fcd5dd1b6b49d84abcf3feaf47d6fe60383b9cdfbea6e');
const saved=()=>X.deserialize(BYTES.toString('utf8')),eq=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} versus ${b}`);
// The source was earned entirely with normal actions in natural-depth.test.
// This suite declares position/projectile boundaries for exact effect comparisons.
function pair(npc,map='sect'){const base=saved();atStation(base,npc,map);const boost=X.deserialize(X.serialize(base)),support=X.relationshipInfo(boost,npc).supports[0],before=ledger(boost);checked(boost,`journey:npc:${npc}:support:${support.id}`);for(const[k,n]of Object.entries(support.cost))assert.equal(boost.player[k],before.wallet[k]-n);assert.equal(boost.journey.supports[support.id],120);failed(boost,`journey:npc:${npc}:support:${support.id}`);roundtrip(boost);return{base,boost,id:support.id};}
function production(s,facility,recipe){if(s.mapId!=='sect')checked(s,'travel:sect');checked(s,`management:order:${facility}:${recipe}:1`);X.step(s,{},.05);return s.management.facilities[facility].batch;}
function incoming(s){if(s.mapId!=='main')checked(s,'travel:main');s.player.x=1100;s.player.y=1800;s.player.invuln=0;s.player.shield=0;const before=s.player.hp;s.projectiles.push({x:s.player.x,y:s.player.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:s.enemies[0].id,damage:200});X.step(s,{},.05);return before-s.player.hp;}
test('genuinely completed herbal and artisan relationships produce faster real batches with identical paid recipes',()=>{
 for(const[npc,map,worker,facility,recipe,mult]of[['herbalist','main','qinghe','garden','timber',1.15],['fireArtisan','red','yanming','forge','iron',1.2]]){const{base,boost}=pair(npc,map),a=production(base,facility,recipe),b=production(boost,facility,recipe);assert.equal(X.relationshipBonus(boost,worker),mult);eq(a.duration/b.duration,mult);assert.deepEqual(a.cost,b.cost);assert.deepEqual(a.reward,b.reward);roundtrip(base);roundtrip(boost);const sb=boost.management.facilities[facility];advance(boost,b.duration+.1);assert.equal(sb.stored.length,1);const before=ledger(boost);checked(boost,'management:claim:'+facility);for(const[k,n]of Object.entries(b.reward))assert.equal(boost.player[k],before.wallet[k]+n);roundtrip(boost);}
});
test('herbal support reduces real incoming damage by ten percent rather than merely changing a preview',()=>{
 const{base,boost}=pair('herbalist','main'),a=incoming(base),b=incoming(boost);eq(b/a,.9);roundtrip(base);roundtrip(boost);
});
test('elder support improves actual earned research XP and expires without free extension or save failure',()=>{
 const{base,boost}=pair('elder');for(const s of[base,boost]){const b=production(s,'library','insight');advance(s,b.duration+.1);}const a=base.player.xp,b=boost.player.xp;checked(base,'management:claim:library');checked(boost,'management:claim:library');eq((boost.player.xp-b)/(base.player.xp-a),1.15);roundtrip(boost);const paused=ledger(boost);X.step(boost,{},0);assert.deepEqual(ledger(boost),paused);advance(boost,121);assert.equal(boost.journey.supports.study,0);roundtrip(boost);
});
function escort(s){const bot=naturalBot(s);checked(s,'journey:build:equip:0:none');checked(s,'journey:build:equip:1:none');bot.action('journey:route:start:herbTrail');for(const choice of ['guard','raid']){bot.walk(X.expeditionInfo(s).station);bot.action('journey:route:choose:'+choice);for(const e of[...s.enemies])if(e.hp>0)bot.fight(e);}bot.walk(X.expeditionInfo(s).station);bot.action('journey:route:choose:escort');roundtrip(s);return s.journey.active.objective;}
test('disciple support reduces actual escort-cart projectile damage and provides dash preparation without an equipped mindset',()=>{
 const{base,boost}=pair('disciple'),a=escort(base),b=escort(boost);assert.ok(boost.journey.supports.escort>0);for(const s of[base,boost]){const o=s.journey.active.objective;s.projectiles.push({x:o.x,y:o.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:s.enemies[0].id,damage:100});X.step(s,{},.05);}eq((b.maxHp-b.hp)/(a.maxHp-a.hp),.7);X.step(boost,{dash:true,mx:1},.05);assert.ok(boost.journey.build.armed.windUntil>boost.time);roundtrip(base);roundtrip(boost);
});
test('real death freezes earned support while global time advances, and the revived save remains valid',()=>{
 const{boost}=pair('herbalist','main');boost.player.x=1100;boost.player.y=1800;boost.player.invuln=0;boost.player.shield=0;boost.projectiles.push({x:boost.player.x,y:boost.player.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:boost.enemies[0].id,damage:100000});X.step(boost,{},.05);assert.equal(boost.dead,true);assert.equal(boost.player.hp,0);const life=boost.journey.supports.herbal,time=boost.time,stopped=ledger(boost);for(let i=0;i<2600;i++)X.step(boost,{},.05);eq(boost.time-time,130);assert.equal(boost.journey.supports.herbal,life);assert.deepEqual(ledger(boost),stopped);roundtrip(boost);checked(boost,'revive');roundtrip(boost);advance(boost,life+.1);assert.equal(boost.journey.supports.herbal,0);roundtrip(boost);
});
