'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {X,C,ledger,checked,failed,step,advance,roundtrip,atStation,naturalBot}=require('./depth-helpers.cjs');
const BYTES=fs.readFileSync(path.join(__dirname,'v6-depth.fixture.json'));
assert.equal(crypto.createHash('sha256').update(BYTES).digest('hex'),'51ba4153e63d8babb98fcd5dd1b6b49d84abcf3feaf47d6fe60383b9cdfbea6e');
const fresh=()=>X.deserialize(BYTES.toString('utf8')),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} vs ${b}`),qi=(s,id)=>X.worldQuestInfo(s).find(q=>q.id===id);
const normalizedJourney=j=>{const a=structuredClone(j);for(const r of[a.retreat,...a.cultivation.sessions])if(r)for(const k of ['pressure','stableTime'])r[k]=Math.round(r[k]*1e6)/1e6;return a;};
function npc(s,bot,id){bot.walk(X.mapInfo(s).npcs.find(n=>n.id===id));X.interact(s);assert.equal(s.interaction,'worldlife:'+id);if(!s.worldlife.met.includes(id))bot.action('worldlife:npc:talk:'+id);}
function boundaryNpc(s,id){const n=C.WORLD_NPCS[id];atStation(s,id,n.mapId);if(!s.worldlife.met.includes(id))checked(s,'worldlife:npc:talk:'+id);}
function gather(s,bot,count){const start=s.progress.gathered.herbs||0;bot.travel('main');for(let i=0;(s.progress.gathered.herbs||0)-start<count;i++){assert.ok(i<40);const nodes=s.nodes.filter(n=>n.type==='herb'&&n.ready<=0).sort((a,b)=>Math.hypot(a.x-s.player.x,a.y-s.player.y)-Math.hypot(b.x-s.player.x,b.y-s.player.y));assert.ok(nodes.length);bot.walk(nodes[0]);bot.frame({interact:true});}}
let result;
function natural(){if(result)return result;const s=fresh(),bot=naturalBot(s),proof=[],original=ledger(s),oldNpc=structuredClone(s.npcProgress);bot.action('technique:flame_immortal');bot.action('secondary:wood');
 for(const mapId of C.EXPANSION_MAP_IDS){bot.travel(mapId);const npcs=Object.values(C.WORLD_NPCS).filter(n=>n.mapId===mapId);for(const n of npcs){npc(s,bot,n.id);const q=Object.values(C.WORLD_QUESTS).find(q=>q.npcId===n.id);bot.action('worldlife:quest:accept:'+q.id);assert.equal(qi(s,q.id).progress,0);failed(s,'worldlife:quest:claim:'+q.id);}
  for(const q of Object.values(C.WORLD_QUESTS).filter(q=>q.mapId===mapId&&q.kind==='kill')){for(let loop=0;qi(s,q.id).progress<q.target;loop++){assert.ok(loop<12,'Enough naturally respawning '+q.enemyType);const enemies=s.enemies.filter(e=>e.type===q.enemyType&&e.hp>0);if(!enemies.length){bot.walk(X.mapInfo(s).start);bot.wait(66);continue;}for(const e of enemies){if(qi(s,q.id).progress>=q.target)break;bot.walk(e);if(e.hp>0)bot.fight(e);}}roundtrip(s);}
  for(const n of npcs){npc(s,bot,n.id);const first=qi(s,Object.values(C.WORLD_QUESTS).find(q=>q.npcId===n.id).id),before=ledger(s);bot.action('worldlife:quest:claim:'+first.id);for(const[k,v]of Object.entries(first.reward)){if(k==='xp')assert.ok(s.player.xp>before.wallet.xp);else if(k in before.wallet)assert.equal(s.player[k],before.wallet[k]+v);else assert.equal(s.inventory[k],(before.inventory[k]||0)+v);}failed(s,'worldlife:quest:claim:'+first.id);const next=Object.values(C.WORLD_QUESTS).find(q=>q.npcId===n.id&&q.prerequisites.length);bot.action('worldlife:quest:accept:'+next.id);if(next.kind==='gather'){assert.equal(qi(s,next.id).progress,0);gather(s,bot,next.target);bot.travel(mapId);}if(next.kind==='visit'){assert.equal(qi(s,next.id).progress,0);bot.travel(next.targetMap);bot.travel(mapId);}npc(s,bot,n.id);const paid=ledger(s);bot.action('worldlife:quest:claim:'+next.id);for(const[k,v]of Object.entries(next.cost||{}))assert.equal(s.player[k],paid.wallet[k]-v+(next.reward[k]||0));failed(s,'worldlife:quest:claim:'+next.id);failed(s,'worldlife:quest:accept:'+next.id);roundtrip(s);proof.push({npc:n.id,mapId,quests:[first.id,next.id],cost:next.cost||{},time:s.time,kills:structuredClone(s.worldlife.kills)});}
 }
 assert.equal(Object.values(s.worldlife.quests).filter(q=>q.claimedAt!=null).length,24);assert.equal(s.worldlife.met.length,12);assert.deepEqual(s.npcProgress,oldNpc);assert.equal(X.talentInfo(s).pointsEarned,16);bot.travel('mistTown');npc(s,bot,'yueLing');bot.action('worldlife:romance:gift:yueLing');assert.equal(X.worldNpcInfo(s,'yueLing').romance.affinity,6);const beforeBond=X.serialize(s);bot.action('worldlife:romance:bond:yueLing');bot.action('worldlife:romance:travel:yueLing');npc(s,bot,'emptyHand');const beforeThief=X.serialize(s);bot.action('worldlife:thief:mercy');bot.travel('sect');bot.action('worldlife:trait:train:qinghe:loyal');for(const id of ['martialBody','martialEdge','martialGuard','spiritPool','spiritBreath','spiritEconomy','lifeLore','lifeGather','lifeArtisan','lifePatience','lifeCompanion','lifeMaster'])bot.action('worldlife:talent:learn:'+id);roundtrip(s);assert.equal(s.dead,false);result={s,beforeBond,beforeThief,proof,original,metrics:bot.metrics(),trace:bot.trace};const out=process.env.SHANHAI_V7_OUTPUT&&path.resolve(process.env.SHANHAI_V7_OUTPUT);if(out){fs.mkdirSync(out,{recursive:true});for(const [name,data]of Object.entries({'natural-world-save.json':X.serialize(s),'natural-before-bond.json':beforeBond,'natural-before-thief.json':beforeThief,'natural-world-report.json':JSON.stringify({boundary:'Immutable earned V6 fixture; only paid gameplay actions and normal movement, aim, attack, Q/F, dash and gather input. No position, HP, MP, materials, enemy, stage, reward or progression assignments.',proof,metrics:result.metrics,trace:bot.trace,initial:original.wallet,final:ledger(s).wallet},null,2)}))fs.writeFileSync(path.join(out,name),data);}return result;
}

test('real V1 through V6 saves use original catalogs, retain earned progress and initialize empty V7 frontier records',()=>{
 for(let v=1;v<=6;v++){const raw=fs.readFileSync(path.join(__dirname,v===6?'v6-depth.fixture.json':`v${v}-save.fixture.json`),'utf8'),old=JSON.parse(raw),s=X.deserialize(raw);assert.equal(s.version,7);assert.deepEqual(s.worldlife.met,[]);assert.deepEqual(s.worldlife.quests,{});assert.deepEqual(s.worldlife.talents,[]);assert.equal(s.worldlife.partner,null);roundtrip(s);if(v===6)for(const k of ['workshop','management','journey'])assert.deepEqual(k==='journey'?normalizedJourney(JSON.parse(X.serialize(s))[k]):JSON.parse(X.serialize(s))[k],k==='journey'?normalizedJourney(old[k]):old[k]);const mapBad=JSON.parse(raw);mapBad.mapId='mistTown';if(v===1)assert.equal(X.deserialize(JSON.stringify(mapBad)).mapId,'main','V1 has no mapId field; ignore unknown map and never create frontier progress');else assert.throws(()=>X.deserialize(JSON.stringify(mapBad)));const socialBad=JSON.parse(raw);socialBad.worldlife={schema:1,met:['yueLing']};assert.throws(()=>X.deserialize(JSON.stringify(socialBad)));const enemyBad=JSON.parse(raw);if(v===1)enemyBad.enemies[0].type='streetBandit';else enemyBad.worlds.main.enemies[0].type='streetBandit';assert.throws(()=>X.deserialize(JSON.stringify(enemyBad)));if(v>1){const worldBad=JSON.parse(raw);worldBad.worlds.mistTown=structuredClone(worldBad.worlds.main);worldBad.progress.visited.push('mistTown');assert.throws(()=>X.deserialize(JSON.stringify(worldBad)));}}
});

test('normal input completes all four frontier maps and every two-part character chain, bonds a companion and pays for training',t=>{const r=natural();t.diagnostic(JSON.stringify({boundary:'Normal actions and input only',maps:C.EXPANSION_MAP_IDS,npcs:r.s.worldlife.met.length,claimed:24,talents:r.s.worldlife.talents,partner:r.s.worldlife.partner,thief:r.s.worldlife.thief,metrics:r.metrics}));});

test('all 24 quests require their issuer, real post-accept events, prerequisites, costs and one-time claims',()=>{
 const earned=natural();for(const q of Object.values(C.WORLD_QUESTS)){const s=fresh();boundaryNpc(s,q.npcId);if(q.prerequisites.length)failed(s,'worldlife:quest:accept:'+q.id);else{const before=ledger(s);checked(s,'worldlife:quest:accept:'+q.id);assert.deepEqual(ledger(s).wallet,before.wallet);assert.equal(qi(s,q.id).progress,0);failed(s,'worldlife:quest:claim:'+q.id);failed(s,'worldlife:quest:accept:'+q.id);checked(s,'travel:sect');failed(s,'worldlife:quest:claim:'+q.id);}const end=X.deserialize(X.serialize(earned.s));boundaryNpc(end,q.npcId);failed(end,'worldlife:quest:claim:'+q.id);}
});

test('V7 rejects invented quest chains, unearned talent points, invalid partners, gift caps and unauthorized traits',()=>{
 const raw=X.serialize(natural().s);for(const mutate of [d=>d.worldlife.met.push('missing'),d=>d.worldlife.quests.moonSteel.baseline+=1000,d=>d.worldlife.quests.moonSteel.claimedAt=d.time+1,d=>d.worldlife.quests.moonPromise.acceptedAt=0,d=>d.worldlife.talents.push('martialMaster'),d=>d.worldlife.talents=Object.keys(C.TALENTS),d=>d.worldlife.partner='pillMaster',d=>d.worldlife.companion='yunSheng',d=>d.worldlife.relations.yueLing.gifts=4,d=>d.worldlife.discipleTraits.qinghe='careful',d=>d.worldlife.thief='missing',d=>d.worldlife.poison={life:0,damage:2,tick:0}]){const bad=JSON.parse(raw);mutate(bad);assert.throws(()=>X.deserialize(JSON.stringify(bad)));}roundtrip(natural().s);
});

test('both adult companions require their complete chains, paid gifts and unique commitment, then restore real battle HP or MP',()=>{
 const start=natural().beforeBond;for(const id of ['yueLing','yunSheng']){const s=X.deserialize(start);boundaryNpc(s,id);assert.ok(X.worldNpcInfo(s,id).age>=18);if(id==='yunSheng')checked(s,'worldlife:romance:gift:'+id);const before=ledger(s);checked(s,'worldlife:romance:bond:'+id);assert.equal(s.player.stones,before.wallet.stones-80);assert.equal(s.player.core,before.wallet.core-2);checked(s,'worldlife:romance:travel:'+id);failed(s,'worldlife:romance:bond:'+id);for(let i=X.worldNpcInfo(s,id).romance.gifts;i<3;i++)checked(s,'worldlife:romance:gift:'+id);failed(s,'worldlife:romance:gift:'+id);roundtrip(s);
  // Explicit battle effect boundary: lower HP/MP and place at a real unsafe map position.
  s.player.x=1800;s.player.y=2200;for(const e of s.enemies)e.stun=20;const field=id==='yueLing'?'hp':'mp',max=field==='hp'?X.stats(s).maxHp:X.stats(s).maxMp;s.player[field]=max*.4;const initial=s.player[field];step(s);near(s.player[field]-initial,max*(field==='hp'?.05:.08)+(field==='mp'?(2.5+X.stats(s).manaRegen)*.05:0));assert.equal(s.worldlife.companionCd,12);const next=s.player[field];advance(s,.5);near(s.player[field]-next,field==='mp'?(2.5+X.stats(s).manaRegen)*.5:0);roundtrip(s);boundaryNpc(s,id);checked(s,'worldlife:romance:travel:'+id);assert.equal(s.worldlife.companion,null);boundaryNpc(s,id==='yueLing'?'yunSheng':'yueLing');failed(s,'worldlife:romance:bond:'+(id==='yueLing'?'yunSheng':'yueLing'));}
 const none=fresh();boundaryNpc(none,'yueLing');failed(none,'worldlife:romance:bond:yueLing');failed(none,'worldlife:romance:travel:yueLing');
});

test('thief choices exchange exact earned money and materials once and unlock only their matching paid training',()=>{
 for(const choice of ['mercy','justice']){const s=X.deserialize(natural().beforeThief);boundaryNpc(s,'emptyHand');const before=ledger(s);checked(s,'worldlife:thief:'+choice);assert.equal(s.player.stones,before.wallet.stones+(choice==='mercy'?-20:45));assert.equal(s.player[choice==='mercy'?'spiritwood':'iron'],before.wallet[choice==='mercy'?'spiritwood':'iron']+4);if(choice==='mercy')assert.ok(s.player.xp>before.wallet.xp);failed(s,'worldlife:thief:'+choice);failed(s,'worldlife:thief:'+(choice==='mercy'?'justice':'mercy'));checked(s,'travel:sect');const trait=choice==='mercy'?'loyal':'careful',pay=ledger(s);checked(s,'worldlife:trait:train:qinghe:'+trait);assert.equal(s.player.stones,pay.wallet.stones-45);assert.equal(s.player.essence,pay.wallet.essence-1);failed(s,'worldlife:trait:train:qinghe:'+trait);failed(s,'worldlife:trait:train:qinghe:'+(choice==='mercy'?'careful':'loyal'));roundtrip(s);}
});

test('all eighteen talent nodes spend earned points, enforce ordered paths and actually change stats or resource effects',()=>{
 const raw=natural().beforeBond;for(const pathId of ['martial','spirit','life']){const s=X.deserialize(raw);checked(s,'travel:sect');const chain=Object.values(C.TALENTS).filter(t=>t.path===pathId);failed(s,'worldlife:talent:learn:'+chain[5].id);for(const t of chain){const old=X.stats(s),wallet=ledger(s).wallet,points=X.talentInfo(s).pointsAvailable;checked(s,'worldlife:talent:learn:'+t.id);assert.equal(X.talentInfo(s).pointsAvailable,points-1);assert.deepEqual(ledger(s).wallet,wallet);const now=X.stats(s);for(const[k,v]of Object.entries(t.effects))if(k in old)near(now[k]-old[k],v);failed(s,'worldlife:talent:learn:'+t.id);roundtrip(s);}assert.equal(s.worldlife.talents.length,6);}
 const empty=X.createGame(109);checked(empty,'worldlife:talent:learn:martialBody');failed(empty,'worldlife:talent:learn:martialEdge');
});

function talentBranch(pathId,count){const s=X.deserialize(natural().beforeBond);checked(s,'travel:sect');for(const t of Object.values(C.TALENTS).filter(t=>t.path===pathId).slice(0,count))checked(s,'worldlife:talent:learn:'+t.id);return s;}
function incoming(s){checked(s,'travel:main');s.player.x=1100;s.player.y=1800;s.player.invuln=0;s.player.shield=0;const old=s.player.hp;s.projectiles.push({x:s.player.x,y:s.player.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:s.enemies[0].id,damage:200});step(s);return old-s.player.hp;}
test('martial resilience reduces an actual projectile hit and movement/HP/attack talents retain strict saved effects',()=>{const a=talentBranch('martial',4),b=talentBranch('martial',5);near(incoming(b)/incoming(a),.92);roundtrip(a);roundtrip(b);});
test('spirit economy changes actual Q spending while breath and mastery restore real MP on normal ticks',()=>{const a=talentBranch('spirit',2),b=talentBranch('spirit',3);for(const s of [a,b]){checked(s,'technique:flame_immortal');checked(s,'travel:main');s.player.x=1100;s.player.y=1800;s.player.skillCd=0;s.player.mp=100;const old=s.player.mp,regen=2.5+X.stats(s).manaRegen,cost=X.techniqueInfo(s).manaCost;step(s,{skill:true,aimX:1500,aimY:1800});near(old-s.player.mp,cost-regen*.05);}assert.ok(X.techniqueInfo(b).manaCost<X.techniqueInfo(a).manaCost);const master=talentBranch('spirit',6);master.player.mp=100;const old=master.player.mp;advance(master,1);near(master.player.mp-old,6+X.stats(master).manaRegen);roundtrip(master);});

function production(s,id='garden',recipe='timber'){for(const f of Object.keys(s.management.facilities))checked(s,'management:cancel:'+f);checked(s,`management:order:${id}:${recipe}:1`);step(s);return s.management.facilities[id].batch;}
test('life gathering, XP, workshop speed and fatigue talents change actual collection, rewards and finished batches',()=>{
 const base=talentBranch('life',1),gathered=talentBranch('life',2);for(const s of [base,gathered]){checked(s,'travel:main');const node=s.nodes.find(n=>n.type==='crystal'&&n.ready<=0);s.player.x=node.x;s.player.y=node.y;const before=s.player.stones;X.interact(s);assert.equal(s.lastAction.ok,true);s.__yield=s.player.stones-before;}assert.ok(gathered.__yield>base.__yield);delete base.__yield;delete gathered.__yield;
 const a=talentBranch('life',2),b=talentBranch('life',3),c=talentBranch('life',4),ab=production(a),bb=production(b),cb=production(c);near(ab.duration/bb.duration,1.08);near(bb.duration,cb.duration);const beforeB=b.management.workers.qinghe.fatigue,beforeC=c.management.workers.qinghe.fatigue;advance(b,bb.duration+.1);advance(c,cb.duration+.1);assert.ok(c.management.workers.qinghe.fatigue-beforeC<b.management.workers.qinghe.fatigue-beforeB);roundtrip(b);roundtrip(c);
 const normal=fresh(),boost=talentBranch('life',6);const initial=normal.player.xp,initialBoost=boost.player.xp;for(const s of [normal,boost]){const batch=production(s,'library','insight');advance(s,batch.duration+.1);checked(s,'management:claim:library');}near((boost.player.xp-initialBoost)/(normal.player.xp-initial),1.06*1.1);
});

test('paid temperament replaces one trait and changes real next-batch duration, fatigue and battle stats without stacking',()=>{
 const base=fresh();if(base.mapId!=='sect')checked(base,'travel:sect');const bare=X.stats(base);const a=X.deserialize(X.serialize(base)),b=X.deserialize(X.serialize(base));checked(b,'worldlife:trait:train:qinghe:gifted');const ab=production(a),bb=production(b);near(ab.duration/bb.duration,1.18/1.15);const af=a.management.workers.qinghe.fatigue,bf=b.management.workers.qinghe.fatigue;advance(a,ab.duration+.1);advance(b,bb.duration+.1);assert.ok(b.management.workers.qinghe.fatigue-bf>a.management.workers.qinghe.fatigue-af);checked(b,'worldlife:trait:train:qinghe:spirited');near(X.stats(b).maxMp-bare.maxMp,10);assert.deepEqual(X.discipleTraitInfo(b).find(d=>d.id==='qinghe').traits.map(t=>t.id),['spirited']);roundtrip(b);
});

// Isolated AI boundary: existing naturally generated enemy and world, fixed
// player distance and temporary stuns for other monsters; no synthetic reward.
function aiFixture(type){const s=fresh(),mapId=C.EXPANSION_MAP_IDS.find(id=>C.MAPS[id].spawns.some(v=>v[0]===type));checked(s,'travel:'+mapId);const e=s.enemies.find(e=>e.type===type);for(const other of s.enemies)if(other!==e)other.stun=20;s.player.x=e.x+65;s.player.y=e.y;s.player.invuln=0;s.player.shield=0;return{s,e};}
test('all twelve frontier enemies actually telegraph, attack and hurt or emit their distinct projectiles',t=>{
 const proof=[];for(const[type,spec]of Object.entries(C.EXPANSION_ENEMIES)){const{s,e}=aiFixture(type),hp=s.player.hp,start={x:e.x,y:e.y},observed={warning:false,projectiles:0,damage:0,movement:0};for(let i=0;i<100;i++){const nativePush=s.projectiles.push;let emitted=0;s.projectiles.push=function(...items){emitted+=items.filter(b=>b.owner==='enemy'&&b.sourceId===e.id).length;return nativePush.apply(this,items);};step(s);observed.projectiles=Math.max(observed.projectiles,emitted);observed.warning ||= s.effects.some(f=>f.type==='warning'&&f.sourceId===e.id);observed.projectiles=Math.max(observed.projectiles,s.projectiles.filter(b=>b.owner==='enemy'&&b.sourceId===e.id).length);}observed.damage=hp-s.player.hp;observed.movement=Math.hypot(e.x-start.x,e.y-start.y);assert.ok(e.phase>0,type+' must complete real attacks');assert.ok(observed.warning,type+' must telegraph');assert.ok(observed.damage>0||observed.projectiles>0,type+' must hurt or shoot');if(['ink','song','wave','poison','drain','prism'].includes(spec.behavior))assert.ok(observed.projectiles>=({ink:3,song:10,wave:3,poison:3,drain:1,prism:8}[spec.behavior]),type+' real projectile pattern');roundtrip(s);proof.push({type,body:spec.bodyKind,behavior:spec.behavior,...observed});}assert.equal(new Set(proof.map(p=>p.body)).size,12);assert.equal(new Set(proof.map(p=>p.behavior)).size,12);t.diagnostic(JSON.stringify(proof));
});

test('bandit actual unblocked hits steal at most the tracked cap and its real kill returns every stolen stone',()=>{
 const{s,e}=aiFixture('streetBandit'),initial=s.player.stones,key=s.mapId+':'+e.id;let previous=0;for(let i=0;i<1000;i++){for(const other of s.enemies)if(other!==e)other.stun=20;s.player.x=e.x+35;s.player.y=e.y;step(s);const current=s.worldlife.stolen[key]||0;if(current>previous){assert.ok(current-previous<=12);previous=current;}if(current===120)break;}assert.equal(s.worldlife.stolen[key],120);assert.equal(s.player.stones,initial-120);roundtrip(s);for(let i=0;i<150;i++){for(const other of s.enemies)if(other!==e)other.stun=20;s.player.x=e.x+35;s.player.y=e.y;step(s);}assert.equal(s.player.stones,initial-120,'cap must stop deduction rather than discard its record');const before=s.player.stones,bot=naturalBot(s);bot.fight(e);bot.walk(e);bot.wait(.1);assert.equal(s.worldlife.stolen[key],undefined);assert.equal(s.player.stones,before+120+C.EXPANSION_ENEMIES.streetBandit.stones);atStation(s,'yueLing','mistTown');roundtrip(s);
 const blocked=aiFixture('streetBandit');blocked.s.player.invuln=20;const wallet=blocked.s.player.stones;advance(blocked.s,4);assert.equal(blocked.s.player.stones,wallet);assert.deepEqual(blocked.s.worldlife.stolen,{});
});

test('actual scorpion needle causes saved poison ticks and moth dust drains MP while healing the attacker',()=>{
 const poison=aiFixture('sandScorpion');for(let i=0;i<100&&poison.s.worldlife.poison.life===0;i++)step(poison.s);assert.ok(poison.s.worldlife.poison.life>0);assert.ok(poison.s.worldlife.poison.damage>0);roundtrip(poison.s);poison.e.stun=20;poison.s.projectiles.length=0;const hp=poison.s.player.hp;advance(poison.s,.8);assert.ok(poison.s.player.hp<hp,'actual injected toxin continues DOT after needle');advance(poison.s,4);assert.deepEqual(poison.s.worldlife.poison,{life:0,damage:0,tick:0});roundtrip(poison.s);
 const moth=aiFixture('graveMoth');moth.e.hp=moth.e.maxHp*.5;moth.s.player.mp=100;const enemyHp=moth.e.hp;let loss=false;for(let i=0;i<100;i++){const before=moth.s.player.mp;step(moth.s);if(moth.s.player.mp<before){loss=true;break;}}assert.ok(loss);assert.ok(moth.e.hp>enemyHp);roundtrip(moth.s);
});

test('real poisoned death freezes its timer, saves strictly, and revival clears the old toxin before battle resumes',()=>{
 const{s,e}=aiFixture('sandScorpion');for(let i=0;i<100&&s.worldlife.poison.life===0;i++)step(s);assert.ok(s.worldlife.poison.life>0);s.player.hp=1;s.player.invuln=0;s.player.shield=0;for(const n of s.enemies)n.stun=20;s.projectiles.push({x:s.player.x,y:s.player.y,vx:0,vy:0,life:1,radius:6,owner:'enemy',sourceId:e.id,damage:C.EXPANSION_ENEMIES.sandScorpion.damage*.7,element:'wood'});X.step(s,{},.05);assert.equal(s.dead,true);const stopped=ledger(s);for(let i=0;i<400;i++)X.step(s,{},.05);assert.deepEqual(ledger(s),stopped);roundtrip(s);checked(s,'revive');assert.deepEqual(s.worldlife.poison,{life:0,damage:0,tick:0});roundtrip(s);
});

function projectileHit(s,e){for(const n of s.enemies)n.stun=20;const hp=e.hp;s.projectiles.push({x:e.x,y:e.y,vx:0,vy:0,life:1,radius:6,owner:'player',sourceId:'player',damage:100,element:'wind',kind:'arrow',weaponKind:'bow'});step(s);return hp-e.hp;}
test('crab frontal shell and sentinel raised shield reduce actual projectile damage',()=>{
 const crab=aiFixture('reefCrab'),back=aiFixture('reefCrab');crab.e.facing=0;back.e.facing=Math.PI;near(projectileHit(crab.s,crab.e)/projectileHit(back.s,back.e),.5);const brace=aiFixture('tombSentinel'),open=aiFixture('tombSentinel');brace.e.mode='windup';brace.e.attackTimer=1;near(projectileHit(brace.s,brace.e)/projectileHit(open.s,open.e),.3);
});

function elementalHit(count,technique){const s=talentBranch('spirit',count);checked(s,'technique:'+technique);checked(s,'travel:buriedPalace');const e=s.enemies.find(e=>e.type==='tombSentinel');for(const n of s.enemies)n.stun=20;e.hp=e.maxHp;s.player.x=e.x+100;s.player.y=e.y;s.player.skillCd=0;s.player.mp=100;const hp=e.hp;step(s,{skill:true,aimX:e.x,aimY:e.y});return hp-e.hp;}
test('fire and frost talent effects increase the actual same spell hit by ten percent',()=>{near(elementalHit(4,'flame')/elementalHit(3,'flame'),1.1);near(elementalHit(5,'frost')/elementalHit(4,'frost'),1.1);});

test('companionship talent shortens a real healing pulse and death freezes companion until revived',()=>{
 const s=X.deserialize(natural().beforeBond);boundaryNpc(s,'yueLing');checked(s,'worldlife:romance:bond:yueLing');checked(s,'worldlife:romance:travel:yueLing');checked(s,'travel:sect');for(const t of Object.values(C.TALENTS).filter(t=>t.path==='life').slice(0,5))checked(s,'worldlife:talent:learn:'+t.id);checked(s,'travel:main');s.player.x=1100;s.player.y=1800;s.player.hp=X.stats(s).maxHp*.5;for(const e of s.enemies)e.stun=20;step(s);assert.equal(s.worldlife.companionCd,9);s.player.invuln=0;s.player.shield=0;s.projectiles.push({x:s.player.x,y:s.player.y,vx:0,vy:0,life:1,radius:9,owner:'enemy',sourceId:s.enemies[0].id,damage:100000});X.step(s,{},.05);assert.equal(s.dead,true);const frozen=ledger(s),time=s.time;for(let i=0;i<1000;i++)X.step(s,{},.05);near(s.time-time,50);assert.deepEqual(ledger(s),frozen);roundtrip(s);checked(s,'revive');advance(s,10);assert.equal(s.worldlife.companionCd,0);roundtrip(s);
});
